//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 08:31:49 PM CEST 
//


package it.vidoc.registro.protesti.lista.anagrafiche.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Testata"/>
 *         &lt;element ref="{}ListaAnagrafiche" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testata",
    "listaAnagrafiche"
})
@XmlRootElement(name = "Risposta")
public class Risposta {

    @XmlElement(name = "Testata", required = true)
    protected TestataType testata;
    @XmlElement(name = "ListaAnagrafiche")
    protected ListaAnagraficheType listaAnagrafiche;

    /**
     * Gets the value of the testata property.
     * 
     * @return
     *     possible object is
     *     {@link TestataType }
     *     
     */
    public TestataType getTestata() {
        return testata;
    }

    /**
     * Sets the value of the testata property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestataType }
     *     
     */
    public void setTestata(TestataType value) {
        this.testata = value;
    }

    /**
     * Gets the value of the listaAnagrafiche property.
     * 
     * @return
     *     possible object is
     *     {@link ListaAnagraficheType }
     *     
     */
    public ListaAnagraficheType getListaAnagrafiche() {
        return listaAnagrafiche;
    }

    /**
     * Sets the value of the listaAnagrafiche property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaAnagraficheType }
     *     
     */
    public void setListaAnagrafiche(ListaAnagraficheType value) {
        this.listaAnagrafiche = value;
    }

}
