package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Infcomuni;
import it.vidoc.mybatis.javamodel.InfcomuniExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InfcomuniMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infcomuni
	 * @mbggenerated
	 */
	int countByExample(InfcomuniExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infcomuni
	 * @mbggenerated
	 */
	int deleteByExample(InfcomuniExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infcomuni
	 * @mbggenerated
	 */
	int insert(Infcomuni record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infcomuni
	 * @mbggenerated
	 */
	int insertSelective(Infcomuni record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infcomuni
	 * @mbggenerated
	 */
	List<Infcomuni> selectByExample(InfcomuniExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infcomuni
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Infcomuni record, @Param("example") InfcomuniExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infcomuni
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Infcomuni record, @Param("example") InfcomuniExample example);
}