package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Infeffetti;
import it.vidoc.mybatis.javamodel.InfeffettiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InfeffettiMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infeffetti
	 * @mbggenerated
	 */
	int countByExample(InfeffettiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infeffetti
	 * @mbggenerated
	 */
	int deleteByExample(InfeffettiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infeffetti
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long progrriga);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infeffetti
	 * @mbggenerated
	 */
	int insert(Infeffetti record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infeffetti
	 * @mbggenerated
	 */
	int insertSelective(Infeffetti record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infeffetti
	 * @mbggenerated
	 */
	List<Infeffetti> selectByExample(InfeffettiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infeffetti
	 * @mbggenerated
	 */
	Infeffetti selectByPrimaryKey(Long progrriga);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infeffetti
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Infeffetti record, @Param("example") InfeffettiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infeffetti
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Infeffetti record, @Param("example") InfeffettiExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infeffetti
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Infeffetti record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table infeffetti
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Infeffetti record);
}