package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Logelab;
import it.vidoc.mybatis.javamodel.LogelabExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogelabMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	int countByExample(LogelabExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	int deleteByExample(LogelabExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer progrriga);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	int insert(Logelab record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	int insertSelective(Logelab record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	List<Logelab> selectByExample(LogelabExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	Logelab selectByPrimaryKey(Integer progrriga);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Logelab record, @Param("example") LogelabExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Logelab record, @Param("example") LogelabExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Logelab record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Logelab record);
}