package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Matrixabilitazioni;
import it.vidoc.mybatis.javamodel.MatrixabilitazioniExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MatrixabilitazioniMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table matrixabilitazioni
	 * @mbggenerated
	 */
	int countByExample(MatrixabilitazioniExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table matrixabilitazioni
	 * @mbggenerated
	 */
	int deleteByExample(MatrixabilitazioniExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table matrixabilitazioni
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer progrriga);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table matrixabilitazioni
	 * @mbggenerated
	 */
	int insert(Matrixabilitazioni record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table matrixabilitazioni
	 * @mbggenerated
	 */
	int insertSelective(Matrixabilitazioni record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table matrixabilitazioni
	 * @mbggenerated
	 */
	List<Matrixabilitazioni> selectByExample(MatrixabilitazioniExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table matrixabilitazioni
	 * @mbggenerated
	 */
	Matrixabilitazioni selectByPrimaryKey(Integer progrriga);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table matrixabilitazioni
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Matrixabilitazioni record,
			@Param("example") MatrixabilitazioniExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table matrixabilitazioni
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Matrixabilitazioni record,
			@Param("example") MatrixabilitazioniExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table matrixabilitazioni
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Matrixabilitazioni record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table matrixabilitazioni
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Matrixabilitazioni record);
}