package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Parole;
import it.vidoc.mybatis.javamodel.ParoleExample;
import it.vidoc.mybatis.javamodel.ParoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	int countByExample(ParoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	int deleteByExample(ParoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(ParoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	int insert(Parole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	int insertSelective(Parole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	List<Parole> selectByExample(ParoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	Parole selectByPrimaryKey(ParoleKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Parole record, @Param("example") ParoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Parole record, @Param("example") ParoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Parole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Parole record);
}