package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strcodcomnas;
import it.vidoc.mybatis.javamodel.StrcodcomnasExample;
import it.vidoc.mybatis.javamodel.StrcodcomnasKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StrcodcomnasMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodcomnas
	 * @mbggenerated
	 */
	int countByExample(StrcodcomnasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodcomnas
	 * @mbggenerated
	 */
	int deleteByExample(StrcodcomnasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodcomnas
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(StrcodcomnasKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodcomnas
	 * @mbggenerated
	 */
	int insert(Strcodcomnas record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodcomnas
	 * @mbggenerated
	 */
	int insertSelective(Strcodcomnas record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodcomnas
	 * @mbggenerated
	 */
	List<Strcodcomnas> selectByExample(StrcodcomnasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodcomnas
	 * @mbggenerated
	 */
	Strcodcomnas selectByPrimaryKey(StrcodcomnasKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodcomnas
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strcodcomnas record, @Param("example") StrcodcomnasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodcomnas
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strcodcomnas record, @Param("example") StrcodcomnasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodcomnas
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strcodcomnas record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodcomnas
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strcodcomnas record);
}