package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strcodfisc;
import it.vidoc.mybatis.javamodel.StrcodfiscExample;
import it.vidoc.mybatis.javamodel.StrcodfiscKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StrcodfiscMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodfisc
	 * @mbggenerated
	 */
	int countByExample(StrcodfiscExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodfisc
	 * @mbggenerated
	 */
	int deleteByExample(StrcodfiscExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodfisc
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(StrcodfiscKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodfisc
	 * @mbggenerated
	 */
	int insert(Strcodfisc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodfisc
	 * @mbggenerated
	 */
	int insertSelective(Strcodfisc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodfisc
	 * @mbggenerated
	 */
	List<Strcodfisc> selectByExample(StrcodfiscExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodfisc
	 * @mbggenerated
	 */
	Strcodfisc selectByPrimaryKey(StrcodfiscKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodfisc
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strcodfisc record, @Param("example") StrcodfiscExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodfisc
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strcodfisc record, @Param("example") StrcodfiscExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodfisc
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strcodfisc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodfisc
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strcodfisc record);
}