package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strcodiceregione;
import it.vidoc.mybatis.javamodel.StrcodiceregioneExample;
import it.vidoc.mybatis.javamodel.StrcodiceregioneKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StrcodiceregioneMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodiceregione
	 * @mbggenerated
	 */
	int countByExample(StrcodiceregioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodiceregione
	 * @mbggenerated
	 */
	int deleteByExample(StrcodiceregioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodiceregione
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(StrcodiceregioneKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodiceregione
	 * @mbggenerated
	 */
	int insert(Strcodiceregione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodiceregione
	 * @mbggenerated
	 */
	int insertSelective(Strcodiceregione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodiceregione
	 * @mbggenerated
	 */
	List<Strcodiceregione> selectByExample(StrcodiceregioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodiceregione
	 * @mbggenerated
	 */
	Strcodiceregione selectByPrimaryKey(StrcodiceregioneKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodiceregione
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strcodiceregione record,
			@Param("example") StrcodiceregioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodiceregione
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strcodiceregione record, @Param("example") StrcodiceregioneExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodiceregione
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strcodiceregione record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodiceregione
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strcodiceregione record);
}