package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strcodprvres;
import it.vidoc.mybatis.javamodel.StrcodprvresExample;
import it.vidoc.mybatis.javamodel.StrcodprvresKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StrcodprvresMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodprvres
	 * @mbggenerated
	 */
	int countByExample(StrcodprvresExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodprvres
	 * @mbggenerated
	 */
	int deleteByExample(StrcodprvresExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodprvres
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(StrcodprvresKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodprvres
	 * @mbggenerated
	 */
	int insert(Strcodprvres record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodprvres
	 * @mbggenerated
	 */
	int insertSelective(Strcodprvres record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodprvres
	 * @mbggenerated
	 */
	List<Strcodprvres> selectByExample(StrcodprvresExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodprvres
	 * @mbggenerated
	 */
	Strcodprvres selectByPrimaryKey(StrcodprvresKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodprvres
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strcodprvres record, @Param("example") StrcodprvresExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodprvres
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strcodprvres record, @Param("example") StrcodprvresExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodprvres
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strcodprvres record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strcodprvres
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strcodprvres record);
}