package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strindir15;
import it.vidoc.mybatis.javamodel.Strindir15Example;
import it.vidoc.mybatis.javamodel.Strindir15Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Strindir15Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir15
	 * @mbggenerated
	 */
	int countByExample(Strindir15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir15
	 * @mbggenerated
	 */
	int deleteByExample(Strindir15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir15
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Strindir15Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir15
	 * @mbggenerated
	 */
	int insert(Strindir15 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir15
	 * @mbggenerated
	 */
	int insertSelective(Strindir15 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir15
	 * @mbggenerated
	 */
	List<Strindir15> selectByExample(Strindir15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir15
	 * @mbggenerated
	 */
	Strindir15 selectByPrimaryKey(Strindir15Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir15
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strindir15 record, @Param("example") Strindir15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir15
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strindir15 record, @Param("example") Strindir15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir15
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strindir15 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir15
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strindir15 record);
}