package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strindir20;
import it.vidoc.mybatis.javamodel.Strindir20Example;
import it.vidoc.mybatis.javamodel.Strindir20Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Strindir20Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir20
	 * @mbggenerated
	 */
	int countByExample(Strindir20Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir20
	 * @mbggenerated
	 */
	int deleteByExample(Strindir20Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir20
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Strindir20Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir20
	 * @mbggenerated
	 */
	int insert(Strindir20 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir20
	 * @mbggenerated
	 */
	int insertSelective(Strindir20 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir20
	 * @mbggenerated
	 */
	List<Strindir20> selectByExample(Strindir20Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir20
	 * @mbggenerated
	 */
	Strindir20 selectByPrimaryKey(Strindir20Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir20
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strindir20 record, @Param("example") Strindir20Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir20
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strindir20 record, @Param("example") Strindir20Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir20
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strindir20 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir20
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strindir20 record);
}