package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strindir03;
import it.vidoc.mybatis.javamodel.Strindir03Example;
import it.vidoc.mybatis.javamodel.Strindir03Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Strindir03Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir03
	 * @mbggenerated
	 */
	int countByExample(Strindir03Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir03
	 * @mbggenerated
	 */
	int deleteByExample(Strindir03Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir03
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Strindir03Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir03
	 * @mbggenerated
	 */
	int insert(Strindir03 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir03
	 * @mbggenerated
	 */
	int insertSelective(Strindir03 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir03
	 * @mbggenerated
	 */
	List<Strindir03> selectByExample(Strindir03Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir03
	 * @mbggenerated
	 */
	Strindir03 selectByPrimaryKey(Strindir03Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir03
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strindir03 record, @Param("example") Strindir03Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir03
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strindir03 record, @Param("example") Strindir03Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir03
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strindir03 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir03
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strindir03 record);
}