package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strindir06;
import it.vidoc.mybatis.javamodel.Strindir06Example;
import it.vidoc.mybatis.javamodel.Strindir06Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Strindir06Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir06
	 * @mbggenerated
	 */
	int countByExample(Strindir06Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir06
	 * @mbggenerated
	 */
	int deleteByExample(Strindir06Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir06
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Strindir06Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir06
	 * @mbggenerated
	 */
	int insert(Strindir06 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir06
	 * @mbggenerated
	 */
	int insertSelective(Strindir06 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir06
	 * @mbggenerated
	 */
	List<Strindir06> selectByExample(Strindir06Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir06
	 * @mbggenerated
	 */
	Strindir06 selectByPrimaryKey(Strindir06Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir06
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strindir06 record, @Param("example") Strindir06Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir06
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strindir06 record, @Param("example") Strindir06Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir06
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strindir06 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir06
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strindir06 record);
}