package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strindir10;
import it.vidoc.mybatis.javamodel.Strindir10Example;
import it.vidoc.mybatis.javamodel.Strindir10Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Strindir10Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir10
	 * @mbggenerated
	 */
	int countByExample(Strindir10Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir10
	 * @mbggenerated
	 */
	int deleteByExample(Strindir10Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir10
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Strindir10Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir10
	 * @mbggenerated
	 */
	int insert(Strindir10 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir10
	 * @mbggenerated
	 */
	int insertSelective(Strindir10 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir10
	 * @mbggenerated
	 */
	List<Strindir10> selectByExample(Strindir10Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir10
	 * @mbggenerated
	 */
	Strindir10 selectByPrimaryKey(Strindir10Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir10
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strindir10 record, @Param("example") Strindir10Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir10
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strindir10 record, @Param("example") Strindir10Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir10
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strindir10 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strindir10
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strindir10 record);
}