package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strnomi04;
import it.vidoc.mybatis.javamodel.Strnomi04Example;
import it.vidoc.mybatis.javamodel.Strnomi04Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Strnomi04Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi04
	 * @mbggenerated
	 */
	int countByExample(Strnomi04Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi04
	 * @mbggenerated
	 */
	int deleteByExample(Strnomi04Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi04
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Strnomi04Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi04
	 * @mbggenerated
	 */
	int insert(Strnomi04 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi04
	 * @mbggenerated
	 */
	int insertSelective(Strnomi04 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi04
	 * @mbggenerated
	 */
	List<Strnomi04> selectByExample(Strnomi04Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi04
	 * @mbggenerated
	 */
	Strnomi04 selectByPrimaryKey(Strnomi04Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi04
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strnomi04 record, @Param("example") Strnomi04Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi04
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strnomi04 record, @Param("example") Strnomi04Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi04
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strnomi04 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi04
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strnomi04 record);
}