package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strnomi07;
import it.vidoc.mybatis.javamodel.Strnomi07Example;
import it.vidoc.mybatis.javamodel.Strnomi07Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Strnomi07Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi07
	 * @mbggenerated
	 */
	int countByExample(Strnomi07Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi07
	 * @mbggenerated
	 */
	int deleteByExample(Strnomi07Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi07
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Strnomi07Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi07
	 * @mbggenerated
	 */
	int insert(Strnomi07 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi07
	 * @mbggenerated
	 */
	int insertSelective(Strnomi07 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi07
	 * @mbggenerated
	 */
	List<Strnomi07> selectByExample(Strnomi07Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi07
	 * @mbggenerated
	 */
	Strnomi07 selectByPrimaryKey(Strnomi07Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi07
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strnomi07 record, @Param("example") Strnomi07Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi07
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strnomi07 record, @Param("example") Strnomi07Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi07
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strnomi07 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi07
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strnomi07 record);
}