package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strnomi15;
import it.vidoc.mybatis.javamodel.Strnomi15Example;
import it.vidoc.mybatis.javamodel.Strnomi15Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Strnomi15Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi15
	 * @mbggenerated
	 */
	int countByExample(Strnomi15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi15
	 * @mbggenerated
	 */
	int deleteByExample(Strnomi15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi15
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Strnomi15Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi15
	 * @mbggenerated
	 */
	int insert(Strnomi15 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi15
	 * @mbggenerated
	 */
	int insertSelective(Strnomi15 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi15
	 * @mbggenerated
	 */
	List<Strnomi15> selectByExample(Strnomi15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi15
	 * @mbggenerated
	 */
	Strnomi15 selectByPrimaryKey(Strnomi15Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi15
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strnomi15 record, @Param("example") Strnomi15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi15
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strnomi15 record, @Param("example") Strnomi15Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi15
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strnomi15 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi15
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strnomi15 record);
}