package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strnomi20;
import it.vidoc.mybatis.javamodel.Strnomi20Example;
import it.vidoc.mybatis.javamodel.Strnomi20Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Strnomi20Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi20
	 * @mbggenerated
	 */
	int countByExample(Strnomi20Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi20
	 * @mbggenerated
	 */
	int deleteByExample(Strnomi20Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi20
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Strnomi20Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi20
	 * @mbggenerated
	 */
	int insert(Strnomi20 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi20
	 * @mbggenerated
	 */
	int insertSelective(Strnomi20 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi20
	 * @mbggenerated
	 */
	List<Strnomi20> selectByExample(Strnomi20Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi20
	 * @mbggenerated
	 */
	Strnomi20 selectByPrimaryKey(Strnomi20Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi20
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strnomi20 record, @Param("example") Strnomi20Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi20
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strnomi20 record, @Param("example") Strnomi20Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi20
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strnomi20 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi20
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strnomi20 record);
}