package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strnomi05;
import it.vidoc.mybatis.javamodel.Strnomi05Example;
import it.vidoc.mybatis.javamodel.Strnomi05Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Strnomi05Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi05
	 * @mbggenerated
	 */
	int countByExample(Strnomi05Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi05
	 * @mbggenerated
	 */
	int deleteByExample(Strnomi05Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi05
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Strnomi05Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi05
	 * @mbggenerated
	 */
	int insert(Strnomi05 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi05
	 * @mbggenerated
	 */
	int insertSelective(Strnomi05 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi05
	 * @mbggenerated
	 */
	List<Strnomi05> selectByExample(Strnomi05Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi05
	 * @mbggenerated
	 */
	Strnomi05 selectByPrimaryKey(Strnomi05Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi05
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strnomi05 record, @Param("example") Strnomi05Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi05
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strnomi05 record, @Param("example") Strnomi05Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi05
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strnomi05 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi05
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strnomi05 record);
}