package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Strnomi10;
import it.vidoc.mybatis.javamodel.Strnomi10Example;
import it.vidoc.mybatis.javamodel.Strnomi10Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Strnomi10Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi10
	 * @mbggenerated
	 */
	int countByExample(Strnomi10Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi10
	 * @mbggenerated
	 */
	int deleteByExample(Strnomi10Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi10
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Strnomi10Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi10
	 * @mbggenerated
	 */
	int insert(Strnomi10 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi10
	 * @mbggenerated
	 */
	int insertSelective(Strnomi10 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi10
	 * @mbggenerated
	 */
	List<Strnomi10> selectByExample(Strnomi10Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi10
	 * @mbggenerated
	 */
	Strnomi10 selectByPrimaryKey(Strnomi10Key key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi10
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strnomi10 record, @Param("example") Strnomi10Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi10
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strnomi10 record, @Param("example") Strnomi10Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi10
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strnomi10 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strnomi10
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strnomi10 record);
}