package it.vidoc.mybatis.javaclient;

import it.vidoc.mybatis.javamodel.Userabilitazioni;
import it.vidoc.mybatis.javamodel.UserabilitazioniExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserabilitazioniMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userabilitazioni
	 * @mbggenerated
	 */
	int countByExample(UserabilitazioniExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userabilitazioni
	 * @mbggenerated
	 */
	int deleteByExample(UserabilitazioniExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userabilitazioni
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer progrriga);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userabilitazioni
	 * @mbggenerated
	 */
	int insert(Userabilitazioni record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userabilitazioni
	 * @mbggenerated
	 */
	int insertSelective(Userabilitazioni record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userabilitazioni
	 * @mbggenerated
	 */
	List<Userabilitazioni> selectByExample(UserabilitazioniExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userabilitazioni
	 * @mbggenerated
	 */
	Userabilitazioni selectByPrimaryKey(Integer progrriga);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userabilitazioni
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Userabilitazioni record,
			@Param("example") UserabilitazioniExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userabilitazioni
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Userabilitazioni record, @Param("example") UserabilitazioniExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userabilitazioni
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Userabilitazioni record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userabilitazioni
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Userabilitazioni record);
}