package it.vidoc.mybatis.javamodel;

import java.util.ArrayList;
import java.util.List;

public class AmedeodateaggExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	public AmedeodateaggExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCciaaIsNull() {
			addCriterion("cciaa is null");
			return (Criteria) this;
		}

		public Criteria andCciaaIsNotNull() {
			addCriterion("cciaa is not null");
			return (Criteria) this;
		}

		public Criteria andCciaaEqualTo(String value) {
			addCriterion("cciaa =", value, "cciaa");
			return (Criteria) this;
		}

		public Criteria andCciaaNotEqualTo(String value) {
			addCriterion("cciaa <>", value, "cciaa");
			return (Criteria) this;
		}

		public Criteria andCciaaGreaterThan(String value) {
			addCriterion("cciaa >", value, "cciaa");
			return (Criteria) this;
		}

		public Criteria andCciaaGreaterThanOrEqualTo(String value) {
			addCriterion("cciaa >=", value, "cciaa");
			return (Criteria) this;
		}

		public Criteria andCciaaLessThan(String value) {
			addCriterion("cciaa <", value, "cciaa");
			return (Criteria) this;
		}

		public Criteria andCciaaLessThanOrEqualTo(String value) {
			addCriterion("cciaa <=", value, "cciaa");
			return (Criteria) this;
		}

		public Criteria andCciaaLike(String value) {
			addCriterion("cciaa like", value, "cciaa");
			return (Criteria) this;
		}

		public Criteria andCciaaNotLike(String value) {
			addCriterion("cciaa not like", value, "cciaa");
			return (Criteria) this;
		}

		public Criteria andCciaaIn(List<String> values) {
			addCriterion("cciaa in", values, "cciaa");
			return (Criteria) this;
		}

		public Criteria andCciaaNotIn(List<String> values) {
			addCriterion("cciaa not in", values, "cciaa");
			return (Criteria) this;
		}

		public Criteria andCciaaBetween(String value1, String value2) {
			addCriterion("cciaa between", value1, value2, "cciaa");
			return (Criteria) this;
		}

		public Criteria andCciaaNotBetween(String value1, String value2) {
			addCriterion("cciaa not between", value1, value2, "cciaa");
			return (Criteria) this;
		}

		public Criteria andDataminIsNull() {
			addCriterion("datamin is null");
			return (Criteria) this;
		}

		public Criteria andDataminIsNotNull() {
			addCriterion("datamin is not null");
			return (Criteria) this;
		}

		public Criteria andDataminEqualTo(String value) {
			addCriterion("datamin =", value, "datamin");
			return (Criteria) this;
		}

		public Criteria andDataminNotEqualTo(String value) {
			addCriterion("datamin <>", value, "datamin");
			return (Criteria) this;
		}

		public Criteria andDataminGreaterThan(String value) {
			addCriterion("datamin >", value, "datamin");
			return (Criteria) this;
		}

		public Criteria andDataminGreaterThanOrEqualTo(String value) {
			addCriterion("datamin >=", value, "datamin");
			return (Criteria) this;
		}

		public Criteria andDataminLessThan(String value) {
			addCriterion("datamin <", value, "datamin");
			return (Criteria) this;
		}

		public Criteria andDataminLessThanOrEqualTo(String value) {
			addCriterion("datamin <=", value, "datamin");
			return (Criteria) this;
		}

		public Criteria andDataminLike(String value) {
			addCriterion("datamin like", value, "datamin");
			return (Criteria) this;
		}

		public Criteria andDataminNotLike(String value) {
			addCriterion("datamin not like", value, "datamin");
			return (Criteria) this;
		}

		public Criteria andDataminIn(List<String> values) {
			addCriterion("datamin in", values, "datamin");
			return (Criteria) this;
		}

		public Criteria andDataminNotIn(List<String> values) {
			addCriterion("datamin not in", values, "datamin");
			return (Criteria) this;
		}

		public Criteria andDataminBetween(String value1, String value2) {
			addCriterion("datamin between", value1, value2, "datamin");
			return (Criteria) this;
		}

		public Criteria andDataminNotBetween(String value1, String value2) {
			addCriterion("datamin not between", value1, value2, "datamin");
			return (Criteria) this;
		}

		public Criteria andDatamaxIsNull() {
			addCriterion("datamax is null");
			return (Criteria) this;
		}

		public Criteria andDatamaxIsNotNull() {
			addCriterion("datamax is not null");
			return (Criteria) this;
		}

		public Criteria andDatamaxEqualTo(String value) {
			addCriterion("datamax =", value, "datamax");
			return (Criteria) this;
		}

		public Criteria andDatamaxNotEqualTo(String value) {
			addCriterion("datamax <>", value, "datamax");
			return (Criteria) this;
		}

		public Criteria andDatamaxGreaterThan(String value) {
			addCriterion("datamax >", value, "datamax");
			return (Criteria) this;
		}

		public Criteria andDatamaxGreaterThanOrEqualTo(String value) {
			addCriterion("datamax >=", value, "datamax");
			return (Criteria) this;
		}

		public Criteria andDatamaxLessThan(String value) {
			addCriterion("datamax <", value, "datamax");
			return (Criteria) this;
		}

		public Criteria andDatamaxLessThanOrEqualTo(String value) {
			addCriterion("datamax <=", value, "datamax");
			return (Criteria) this;
		}

		public Criteria andDatamaxLike(String value) {
			addCriterion("datamax like", value, "datamax");
			return (Criteria) this;
		}

		public Criteria andDatamaxNotLike(String value) {
			addCriterion("datamax not like", value, "datamax");
			return (Criteria) this;
		}

		public Criteria andDatamaxIn(List<String> values) {
			addCriterion("datamax in", values, "datamax");
			return (Criteria) this;
		}

		public Criteria andDatamaxNotIn(List<String> values) {
			addCriterion("datamax not in", values, "datamax");
			return (Criteria) this;
		}

		public Criteria andDatamaxBetween(String value1, String value2) {
			addCriterion("datamax between", value1, value2, "datamax");
			return (Criteria) this;
		}

		public Criteria andDatamaxNotBetween(String value1, String value2) {
			addCriterion("datamax not between", value1, value2, "datamax");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table amedeodateagg
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table amedeodateagg
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}