package it.vidoc.mybatis.javamodel;

public class Contratto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contratto.codcontratto
	 * @mbggenerated
	 */
	private String codcontratto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contratto.tipocontratto
	 * @mbggenerated
	 */
	private String tipocontratto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contratto.datainiziovalidita
	 * @mbggenerated
	 */
	private String datainiziovalidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contratto.datafinevalidita
	 * @mbggenerated
	 */
	private String datafinevalidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contratto.nominativo
	 * @mbggenerated
	 */
	private String nominativo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contratto.codicefiscale
	 * @mbggenerated
	 */
	private String codicefiscale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contratto.telefono
	 * @mbggenerated
	 */
	private String telefono;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contratto.indirizzo
	 * @mbggenerated
	 */
	private String indirizzo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contratto.comune
	 * @mbggenerated
	 */
	private String comune;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contratto.provincia
	 * @mbggenerated
	 */
	private String provincia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contratto.riferimento
	 * @mbggenerated
	 */
	private String riferimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contratto.email
	 * @mbggenerated
	 */
	private String email;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contratto.codcontratto
	 * @return  the value of contratto.codcontratto
	 * @mbggenerated
	 */
	public String getCodcontratto() {
		return codcontratto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contratto.codcontratto
	 * @param codcontratto  the value for contratto.codcontratto
	 * @mbggenerated
	 */
	public void setCodcontratto(String codcontratto) {
		this.codcontratto = codcontratto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contratto.tipocontratto
	 * @return  the value of contratto.tipocontratto
	 * @mbggenerated
	 */
	public String getTipocontratto() {
		return tipocontratto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contratto.tipocontratto
	 * @param tipocontratto  the value for contratto.tipocontratto
	 * @mbggenerated
	 */
	public void setTipocontratto(String tipocontratto) {
		this.tipocontratto = tipocontratto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contratto.datainiziovalidita
	 * @return  the value of contratto.datainiziovalidita
	 * @mbggenerated
	 */
	public String getDatainiziovalidita() {
		return datainiziovalidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contratto.datainiziovalidita
	 * @param datainiziovalidita  the value for contratto.datainiziovalidita
	 * @mbggenerated
	 */
	public void setDatainiziovalidita(String datainiziovalidita) {
		this.datainiziovalidita = datainiziovalidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contratto.datafinevalidita
	 * @return  the value of contratto.datafinevalidita
	 * @mbggenerated
	 */
	public String getDatafinevalidita() {
		return datafinevalidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contratto.datafinevalidita
	 * @param datafinevalidita  the value for contratto.datafinevalidita
	 * @mbggenerated
	 */
	public void setDatafinevalidita(String datafinevalidita) {
		this.datafinevalidita = datafinevalidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contratto.nominativo
	 * @return  the value of contratto.nominativo
	 * @mbggenerated
	 */
	public String getNominativo() {
		return nominativo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contratto.nominativo
	 * @param nominativo  the value for contratto.nominativo
	 * @mbggenerated
	 */
	public void setNominativo(String nominativo) {
		this.nominativo = nominativo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contratto.codicefiscale
	 * @return  the value of contratto.codicefiscale
	 * @mbggenerated
	 */
	public String getCodicefiscale() {
		return codicefiscale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contratto.codicefiscale
	 * @param codicefiscale  the value for contratto.codicefiscale
	 * @mbggenerated
	 */
	public void setCodicefiscale(String codicefiscale) {
		this.codicefiscale = codicefiscale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contratto.telefono
	 * @return  the value of contratto.telefono
	 * @mbggenerated
	 */
	public String getTelefono() {
		return telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contratto.telefono
	 * @param telefono  the value for contratto.telefono
	 * @mbggenerated
	 */
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contratto.indirizzo
	 * @return  the value of contratto.indirizzo
	 * @mbggenerated
	 */
	public String getIndirizzo() {
		return indirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contratto.indirizzo
	 * @param indirizzo  the value for contratto.indirizzo
	 * @mbggenerated
	 */
	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contratto.comune
	 * @return  the value of contratto.comune
	 * @mbggenerated
	 */
	public String getComune() {
		return comune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contratto.comune
	 * @param comune  the value for contratto.comune
	 * @mbggenerated
	 */
	public void setComune(String comune) {
		this.comune = comune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contratto.provincia
	 * @return  the value of contratto.provincia
	 * @mbggenerated
	 */
	public String getProvincia() {
		return provincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contratto.provincia
	 * @param provincia  the value for contratto.provincia
	 * @mbggenerated
	 */
	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contratto.riferimento
	 * @return  the value of contratto.riferimento
	 * @mbggenerated
	 */
	public String getRiferimento() {
		return riferimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contratto.riferimento
	 * @param riferimento  the value for contratto.riferimento
	 * @mbggenerated
	 */
	public void setRiferimento(String riferimento) {
		this.riferimento = riferimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contratto.email
	 * @return  the value of contratto.email
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contratto.email
	 * @param email  the value for contratto.email
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email;
	}
}