package it.vidoc.mybatis.javamodel;

public class Listino {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listino.progrriga
	 * @mbggenerated
	 */
	private Integer progrriga;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listino.numerolistino
	 * @mbggenerated
	 */
	private Integer numerolistino;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listino.codicelistino
	 * @mbggenerated
	 */
	private String codicelistino;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listino.codicebancadati
	 * @mbggenerated
	 */
	private String codicebancadati;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listino.codicerichiesta
	 * @mbggenerated
	 */
	private String codicerichiesta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listino.codicerisposta
	 * @mbggenerated
	 */
	private String codicerisposta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listino.prezzo
	 * @mbggenerated
	 */
	private Double prezzo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listino.dirittisegreteria
	 * @mbggenerated
	 */
	private Double dirittisegreteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listino.onldiff
	 * @mbggenerated
	 */
	private String onldiff;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listino.posneg
	 * @mbggenerated
	 */
	private String posneg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listino.progrriga
	 * @return  the value of listino.progrriga
	 * @mbggenerated
	 */
	public Integer getProgrriga() {
		return progrriga;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listino.progrriga
	 * @param progrriga  the value for listino.progrriga
	 * @mbggenerated
	 */
	public void setProgrriga(Integer progrriga) {
		this.progrriga = progrriga;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listino.numerolistino
	 * @return  the value of listino.numerolistino
	 * @mbggenerated
	 */
	public Integer getNumerolistino() {
		return numerolistino;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listino.numerolistino
	 * @param numerolistino  the value for listino.numerolistino
	 * @mbggenerated
	 */
	public void setNumerolistino(Integer numerolistino) {
		this.numerolistino = numerolistino;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listino.codicelistino
	 * @return  the value of listino.codicelistino
	 * @mbggenerated
	 */
	public String getCodicelistino() {
		return codicelistino;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listino.codicelistino
	 * @param codicelistino  the value for listino.codicelistino
	 * @mbggenerated
	 */
	public void setCodicelistino(String codicelistino) {
		this.codicelistino = codicelistino;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listino.codicebancadati
	 * @return  the value of listino.codicebancadati
	 * @mbggenerated
	 */
	public String getCodicebancadati() {
		return codicebancadati;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listino.codicebancadati
	 * @param codicebancadati  the value for listino.codicebancadati
	 * @mbggenerated
	 */
	public void setCodicebancadati(String codicebancadati) {
		this.codicebancadati = codicebancadati;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listino.codicerichiesta
	 * @return  the value of listino.codicerichiesta
	 * @mbggenerated
	 */
	public String getCodicerichiesta() {
		return codicerichiesta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listino.codicerichiesta
	 * @param codicerichiesta  the value for listino.codicerichiesta
	 * @mbggenerated
	 */
	public void setCodicerichiesta(String codicerichiesta) {
		this.codicerichiesta = codicerichiesta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listino.codicerisposta
	 * @return  the value of listino.codicerisposta
	 * @mbggenerated
	 */
	public String getCodicerisposta() {
		return codicerisposta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listino.codicerisposta
	 * @param codicerisposta  the value for listino.codicerisposta
	 * @mbggenerated
	 */
	public void setCodicerisposta(String codicerisposta) {
		this.codicerisposta = codicerisposta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listino.prezzo
	 * @return  the value of listino.prezzo
	 * @mbggenerated
	 */
	public Double getPrezzo() {
		return prezzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listino.prezzo
	 * @param prezzo  the value for listino.prezzo
	 * @mbggenerated
	 */
	public void setPrezzo(Double prezzo) {
		this.prezzo = prezzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listino.dirittisegreteria
	 * @return  the value of listino.dirittisegreteria
	 * @mbggenerated
	 */
	public Double getDirittisegreteria() {
		return dirittisegreteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listino.dirittisegreteria
	 * @param dirittisegreteria  the value for listino.dirittisegreteria
	 * @mbggenerated
	 */
	public void setDirittisegreteria(Double dirittisegreteria) {
		this.dirittisegreteria = dirittisegreteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listino.onldiff
	 * @return  the value of listino.onldiff
	 * @mbggenerated
	 */
	public String getOnldiff() {
		return onldiff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listino.onldiff
	 * @param onldiff  the value for listino.onldiff
	 * @mbggenerated
	 */
	public void setOnldiff(String onldiff) {
		this.onldiff = onldiff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listino.posneg
	 * @return  the value of listino.posneg
	 * @mbggenerated
	 */
	public String getPosneg() {
		return posneg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listino.posneg
	 * @param posneg  the value for listino.posneg
	 * @mbggenerated
	 */
	public void setPosneg(String posneg) {
		this.posneg = posneg;
	}
}