package it.vidoc.mybatis.javamodel;

import java.util.ArrayList;
import java.util.List;

public class LogelabExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table logelab
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table logelab
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table logelab
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	public LogelabExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table logelab
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table logelab
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andProgrrigaIsNull() {
			addCriterion("progrriga is null");
			return (Criteria) this;
		}

		public Criteria andProgrrigaIsNotNull() {
			addCriterion("progrriga is not null");
			return (Criteria) this;
		}

		public Criteria andProgrrigaEqualTo(Integer value) {
			addCriterion("progrriga =", value, "progrriga");
			return (Criteria) this;
		}

		public Criteria andProgrrigaNotEqualTo(Integer value) {
			addCriterion("progrriga <>", value, "progrriga");
			return (Criteria) this;
		}

		public Criteria andProgrrigaGreaterThan(Integer value) {
			addCriterion("progrriga >", value, "progrriga");
			return (Criteria) this;
		}

		public Criteria andProgrrigaGreaterThanOrEqualTo(Integer value) {
			addCriterion("progrriga >=", value, "progrriga");
			return (Criteria) this;
		}

		public Criteria andProgrrigaLessThan(Integer value) {
			addCriterion("progrriga <", value, "progrriga");
			return (Criteria) this;
		}

		public Criteria andProgrrigaLessThanOrEqualTo(Integer value) {
			addCriterion("progrriga <=", value, "progrriga");
			return (Criteria) this;
		}

		public Criteria andProgrrigaIn(List<Integer> values) {
			addCriterion("progrriga in", values, "progrriga");
			return (Criteria) this;
		}

		public Criteria andProgrrigaNotIn(List<Integer> values) {
			addCriterion("progrriga not in", values, "progrriga");
			return (Criteria) this;
		}

		public Criteria andProgrrigaBetween(Integer value1, Integer value2) {
			addCriterion("progrriga between", value1, value2, "progrriga");
			return (Criteria) this;
		}

		public Criteria andProgrrigaNotBetween(Integer value1, Integer value2) {
			addCriterion("progrriga not between", value1, value2, "progrriga");
			return (Criteria) this;
		}

		public Criteria andDatatimeIsNull() {
			addCriterion("datatime is null");
			return (Criteria) this;
		}

		public Criteria andDatatimeIsNotNull() {
			addCriterion("datatime is not null");
			return (Criteria) this;
		}

		public Criteria andDatatimeEqualTo(String value) {
			addCriterion("datatime =", value, "datatime");
			return (Criteria) this;
		}

		public Criteria andDatatimeNotEqualTo(String value) {
			addCriterion("datatime <>", value, "datatime");
			return (Criteria) this;
		}

		public Criteria andDatatimeGreaterThan(String value) {
			addCriterion("datatime >", value, "datatime");
			return (Criteria) this;
		}

		public Criteria andDatatimeGreaterThanOrEqualTo(String value) {
			addCriterion("datatime >=", value, "datatime");
			return (Criteria) this;
		}

		public Criteria andDatatimeLessThan(String value) {
			addCriterion("datatime <", value, "datatime");
			return (Criteria) this;
		}

		public Criteria andDatatimeLessThanOrEqualTo(String value) {
			addCriterion("datatime <=", value, "datatime");
			return (Criteria) this;
		}

		public Criteria andDatatimeLike(String value) {
			addCriterion("datatime like", value, "datatime");
			return (Criteria) this;
		}

		public Criteria andDatatimeNotLike(String value) {
			addCriterion("datatime not like", value, "datatime");
			return (Criteria) this;
		}

		public Criteria andDatatimeIn(List<String> values) {
			addCriterion("datatime in", values, "datatime");
			return (Criteria) this;
		}

		public Criteria andDatatimeNotIn(List<String> values) {
			addCriterion("datatime not in", values, "datatime");
			return (Criteria) this;
		}

		public Criteria andDatatimeBetween(String value1, String value2) {
			addCriterion("datatime between", value1, value2, "datatime");
			return (Criteria) this;
		}

		public Criteria andDatatimeNotBetween(String value1, String value2) {
			addCriterion("datatime not between", value1, value2, "datatime");
			return (Criteria) this;
		}

		public Criteria andPgmelabIsNull() {
			addCriterion("pgmelab is null");
			return (Criteria) this;
		}

		public Criteria andPgmelabIsNotNull() {
			addCriterion("pgmelab is not null");
			return (Criteria) this;
		}

		public Criteria andPgmelabEqualTo(String value) {
			addCriterion("pgmelab =", value, "pgmelab");
			return (Criteria) this;
		}

		public Criteria andPgmelabNotEqualTo(String value) {
			addCriterion("pgmelab <>", value, "pgmelab");
			return (Criteria) this;
		}

		public Criteria andPgmelabGreaterThan(String value) {
			addCriterion("pgmelab >", value, "pgmelab");
			return (Criteria) this;
		}

		public Criteria andPgmelabGreaterThanOrEqualTo(String value) {
			addCriterion("pgmelab >=", value, "pgmelab");
			return (Criteria) this;
		}

		public Criteria andPgmelabLessThan(String value) {
			addCriterion("pgmelab <", value, "pgmelab");
			return (Criteria) this;
		}

		public Criteria andPgmelabLessThanOrEqualTo(String value) {
			addCriterion("pgmelab <=", value, "pgmelab");
			return (Criteria) this;
		}

		public Criteria andPgmelabLike(String value) {
			addCriterion("pgmelab like", value, "pgmelab");
			return (Criteria) this;
		}

		public Criteria andPgmelabNotLike(String value) {
			addCriterion("pgmelab not like", value, "pgmelab");
			return (Criteria) this;
		}

		public Criteria andPgmelabIn(List<String> values) {
			addCriterion("pgmelab in", values, "pgmelab");
			return (Criteria) this;
		}

		public Criteria andPgmelabNotIn(List<String> values) {
			addCriterion("pgmelab not in", values, "pgmelab");
			return (Criteria) this;
		}

		public Criteria andPgmelabBetween(String value1, String value2) {
			addCriterion("pgmelab between", value1, value2, "pgmelab");
			return (Criteria) this;
		}

		public Criteria andPgmelabNotBetween(String value1, String value2) {
			addCriterion("pgmelab not between", value1, value2, "pgmelab");
			return (Criteria) this;
		}

		public Criteria andRigaIsNull() {
			addCriterion("riga is null");
			return (Criteria) this;
		}

		public Criteria andRigaIsNotNull() {
			addCriterion("riga is not null");
			return (Criteria) this;
		}

		public Criteria andRigaEqualTo(String value) {
			addCriterion("riga =", value, "riga");
			return (Criteria) this;
		}

		public Criteria andRigaNotEqualTo(String value) {
			addCriterion("riga <>", value, "riga");
			return (Criteria) this;
		}

		public Criteria andRigaGreaterThan(String value) {
			addCriterion("riga >", value, "riga");
			return (Criteria) this;
		}

		public Criteria andRigaGreaterThanOrEqualTo(String value) {
			addCriterion("riga >=", value, "riga");
			return (Criteria) this;
		}

		public Criteria andRigaLessThan(String value) {
			addCriterion("riga <", value, "riga");
			return (Criteria) this;
		}

		public Criteria andRigaLessThanOrEqualTo(String value) {
			addCriterion("riga <=", value, "riga");
			return (Criteria) this;
		}

		public Criteria andRigaLike(String value) {
			addCriterion("riga like", value, "riga");
			return (Criteria) this;
		}

		public Criteria andRigaNotLike(String value) {
			addCriterion("riga not like", value, "riga");
			return (Criteria) this;
		}

		public Criteria andRigaIn(List<String> values) {
			addCriterion("riga in", values, "riga");
			return (Criteria) this;
		}

		public Criteria andRigaNotIn(List<String> values) {
			addCriterion("riga not in", values, "riga");
			return (Criteria) this;
		}

		public Criteria andRigaBetween(String value1, String value2) {
			addCriterion("riga between", value1, value2, "riga");
			return (Criteria) this;
		}

		public Criteria andRigaNotBetween(String value1, String value2) {
			addCriterion("riga not between", value1, value2, "riga");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table logelab
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table logelab
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 18 09:27:24 CEST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}