package it.vidoc.mybatis.javamodel;

public class ParoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parole.tipoparola
	 * @mbggenerated
	 */
	private String tipoparola;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parole.parola
	 * @mbggenerated
	 */
	private String parola;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parole.codiceregione
	 * @mbggenerated
	 */
	private String codiceregione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parole.progressivo
	 * @mbggenerated
	 */
	private String progressivo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parole.tipoparola
	 * @return  the value of parole.tipoparola
	 * @mbggenerated
	 */
	public String getTipoparola() {
		return tipoparola;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parole.tipoparola
	 * @param tipoparola  the value for parole.tipoparola
	 * @mbggenerated
	 */
	public void setTipoparola(String tipoparola) {
		this.tipoparola = tipoparola;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parole.parola
	 * @return  the value of parole.parola
	 * @mbggenerated
	 */
	public String getParola() {
		return parola;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parole.parola
	 * @param parola  the value for parole.parola
	 * @mbggenerated
	 */
	public void setParola(String parola) {
		this.parola = parola;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parole.codiceregione
	 * @return  the value of parole.codiceregione
	 * @mbggenerated
	 */
	public String getCodiceregione() {
		return codiceregione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parole.codiceregione
	 * @param codiceregione  the value for parole.codiceregione
	 * @mbggenerated
	 */
	public void setCodiceregione(String codiceregione) {
		this.codiceregione = codiceregione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parole.progressivo
	 * @return  the value of parole.progressivo
	 * @mbggenerated
	 */
	public String getProgressivo() {
		return progressivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parole.progressivo
	 * @param progressivo  the value for parole.progressivo
	 * @mbggenerated
	 */
	public void setProgressivo(String progressivo) {
		this.progressivo = progressivo;
	}
}