package it.vidoc.mybatis.javamodel;

public class Parole extends ParoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parole.kanagra
	 * @mbggenerated
	 */
	private String kanagra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parole.istatprvres
	 * @mbggenerated
	 */
	private String istatprvres;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parole.istatres
	 * @mbggenerated
	 */
	private String istatres;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column parole.datatimeins
	 * @mbggenerated
	 */
	private String datatimeins;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parole.kanagra
	 * @return  the value of parole.kanagra
	 * @mbggenerated
	 */
	public String getKanagra() {
		return kanagra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parole.kanagra
	 * @param kanagra  the value for parole.kanagra
	 * @mbggenerated
	 */
	public void setKanagra(String kanagra) {
		this.kanagra = kanagra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parole.istatprvres
	 * @return  the value of parole.istatprvres
	 * @mbggenerated
	 */
	public String getIstatprvres() {
		return istatprvres;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parole.istatprvres
	 * @param istatprvres  the value for parole.istatprvres
	 * @mbggenerated
	 */
	public void setIstatprvres(String istatprvres) {
		this.istatprvres = istatprvres;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parole.istatres
	 * @return  the value of parole.istatres
	 * @mbggenerated
	 */
	public String getIstatres() {
		return istatres;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parole.istatres
	 * @param istatres  the value for parole.istatres
	 * @mbggenerated
	 */
	public void setIstatres(String istatres) {
		this.istatres = istatres;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column parole.datatimeins
	 * @return  the value of parole.datatimeins
	 * @mbggenerated
	 */
	public String getDatatimeins() {
		return datatimeins;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column parole.datatimeins
	 * @param datatimeins  the value for parole.datatimeins
	 * @mbggenerated
	 */
	public void setDatatimeins(String datatimeins) {
		this.datatimeins = datatimeins;
	}
}