package it.vidoc.mybatis.javamodel;

import java.util.ArrayList;
import java.util.List;

public class ParoleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table parole
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table parole
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table parole
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	public ParoleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table parole
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table parole
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTipoparolaIsNull() {
			addCriterion("tipoparola is null");
			return (Criteria) this;
		}

		public Criteria andTipoparolaIsNotNull() {
			addCriterion("tipoparola is not null");
			return (Criteria) this;
		}

		public Criteria andTipoparolaEqualTo(String value) {
			addCriterion("tipoparola =", value, "tipoparola");
			return (Criteria) this;
		}

		public Criteria andTipoparolaNotEqualTo(String value) {
			addCriterion("tipoparola <>", value, "tipoparola");
			return (Criteria) this;
		}

		public Criteria andTipoparolaGreaterThan(String value) {
			addCriterion("tipoparola >", value, "tipoparola");
			return (Criteria) this;
		}

		public Criteria andTipoparolaGreaterThanOrEqualTo(String value) {
			addCriterion("tipoparola >=", value, "tipoparola");
			return (Criteria) this;
		}

		public Criteria andTipoparolaLessThan(String value) {
			addCriterion("tipoparola <", value, "tipoparola");
			return (Criteria) this;
		}

		public Criteria andTipoparolaLessThanOrEqualTo(String value) {
			addCriterion("tipoparola <=", value, "tipoparola");
			return (Criteria) this;
		}

		public Criteria andTipoparolaLike(String value) {
			addCriterion("tipoparola like", value, "tipoparola");
			return (Criteria) this;
		}

		public Criteria andTipoparolaNotLike(String value) {
			addCriterion("tipoparola not like", value, "tipoparola");
			return (Criteria) this;
		}

		public Criteria andTipoparolaIn(List<String> values) {
			addCriterion("tipoparola in", values, "tipoparola");
			return (Criteria) this;
		}

		public Criteria andTipoparolaNotIn(List<String> values) {
			addCriterion("tipoparola not in", values, "tipoparola");
			return (Criteria) this;
		}

		public Criteria andTipoparolaBetween(String value1, String value2) {
			addCriterion("tipoparola between", value1, value2, "tipoparola");
			return (Criteria) this;
		}

		public Criteria andTipoparolaNotBetween(String value1, String value2) {
			addCriterion("tipoparola not between", value1, value2, "tipoparola");
			return (Criteria) this;
		}

		public Criteria andParolaIsNull() {
			addCriterion("parola is null");
			return (Criteria) this;
		}

		public Criteria andParolaIsNotNull() {
			addCriterion("parola is not null");
			return (Criteria) this;
		}

		public Criteria andParolaEqualTo(String value) {
			addCriterion("parola =", value, "parola");
			return (Criteria) this;
		}

		public Criteria andParolaNotEqualTo(String value) {
			addCriterion("parola <>", value, "parola");
			return (Criteria) this;
		}

		public Criteria andParolaGreaterThan(String value) {
			addCriterion("parola >", value, "parola");
			return (Criteria) this;
		}

		public Criteria andParolaGreaterThanOrEqualTo(String value) {
			addCriterion("parola >=", value, "parola");
			return (Criteria) this;
		}

		public Criteria andParolaLessThan(String value) {
			addCriterion("parola <", value, "parola");
			return (Criteria) this;
		}

		public Criteria andParolaLessThanOrEqualTo(String value) {
			addCriterion("parola <=", value, "parola");
			return (Criteria) this;
		}

		public Criteria andParolaLike(String value) {
			addCriterion("parola like", value, "parola");
			return (Criteria) this;
		}

		public Criteria andParolaNotLike(String value) {
			addCriterion("parola not like", value, "parola");
			return (Criteria) this;
		}

		public Criteria andParolaIn(List<String> values) {
			addCriterion("parola in", values, "parola");
			return (Criteria) this;
		}

		public Criteria andParolaNotIn(List<String> values) {
			addCriterion("parola not in", values, "parola");
			return (Criteria) this;
		}

		public Criteria andParolaBetween(String value1, String value2) {
			addCriterion("parola between", value1, value2, "parola");
			return (Criteria) this;
		}

		public Criteria andParolaNotBetween(String value1, String value2) {
			addCriterion("parola not between", value1, value2, "parola");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneIsNull() {
			addCriterion("codiceregione is null");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneIsNotNull() {
			addCriterion("codiceregione is not null");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneEqualTo(String value) {
			addCriterion("codiceregione =", value, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneNotEqualTo(String value) {
			addCriterion("codiceregione <>", value, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneGreaterThan(String value) {
			addCriterion("codiceregione >", value, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneGreaterThanOrEqualTo(String value) {
			addCriterion("codiceregione >=", value, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneLessThan(String value) {
			addCriterion("codiceregione <", value, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneLessThanOrEqualTo(String value) {
			addCriterion("codiceregione <=", value, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneLike(String value) {
			addCriterion("codiceregione like", value, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneNotLike(String value) {
			addCriterion("codiceregione not like", value, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneIn(List<String> values) {
			addCriterion("codiceregione in", values, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneNotIn(List<String> values) {
			addCriterion("codiceregione not in", values, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneBetween(String value1, String value2) {
			addCriterion("codiceregione between", value1, value2, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneNotBetween(String value1, String value2) {
			addCriterion("codiceregione not between", value1, value2, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andProgressivoIsNull() {
			addCriterion("progressivo is null");
			return (Criteria) this;
		}

		public Criteria andProgressivoIsNotNull() {
			addCriterion("progressivo is not null");
			return (Criteria) this;
		}

		public Criteria andProgressivoEqualTo(String value) {
			addCriterion("progressivo =", value, "progressivo");
			return (Criteria) this;
		}

		public Criteria andProgressivoNotEqualTo(String value) {
			addCriterion("progressivo <>", value, "progressivo");
			return (Criteria) this;
		}

		public Criteria andProgressivoGreaterThan(String value) {
			addCriterion("progressivo >", value, "progressivo");
			return (Criteria) this;
		}

		public Criteria andProgressivoGreaterThanOrEqualTo(String value) {
			addCriterion("progressivo >=", value, "progressivo");
			return (Criteria) this;
		}

		public Criteria andProgressivoLessThan(String value) {
			addCriterion("progressivo <", value, "progressivo");
			return (Criteria) this;
		}

		public Criteria andProgressivoLessThanOrEqualTo(String value) {
			addCriterion("progressivo <=", value, "progressivo");
			return (Criteria) this;
		}

		public Criteria andProgressivoLike(String value) {
			addCriterion("progressivo like", value, "progressivo");
			return (Criteria) this;
		}

		public Criteria andProgressivoNotLike(String value) {
			addCriterion("progressivo not like", value, "progressivo");
			return (Criteria) this;
		}

		public Criteria andProgressivoIn(List<String> values) {
			addCriterion("progressivo in", values, "progressivo");
			return (Criteria) this;
		}

		public Criteria andProgressivoNotIn(List<String> values) {
			addCriterion("progressivo not in", values, "progressivo");
			return (Criteria) this;
		}

		public Criteria andProgressivoBetween(String value1, String value2) {
			addCriterion("progressivo between", value1, value2, "progressivo");
			return (Criteria) this;
		}

		public Criteria andProgressivoNotBetween(String value1, String value2) {
			addCriterion("progressivo not between", value1, value2, "progressivo");
			return (Criteria) this;
		}

		public Criteria andKanagraIsNull() {
			addCriterion("kanagra is null");
			return (Criteria) this;
		}

		public Criteria andKanagraIsNotNull() {
			addCriterion("kanagra is not null");
			return (Criteria) this;
		}

		public Criteria andKanagraEqualTo(String value) {
			addCriterion("kanagra =", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraNotEqualTo(String value) {
			addCriterion("kanagra <>", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraGreaterThan(String value) {
			addCriterion("kanagra >", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraGreaterThanOrEqualTo(String value) {
			addCriterion("kanagra >=", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraLessThan(String value) {
			addCriterion("kanagra <", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraLessThanOrEqualTo(String value) {
			addCriterion("kanagra <=", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraLike(String value) {
			addCriterion("kanagra like", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraNotLike(String value) {
			addCriterion("kanagra not like", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraIn(List<String> values) {
			addCriterion("kanagra in", values, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraNotIn(List<String> values) {
			addCriterion("kanagra not in", values, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraBetween(String value1, String value2) {
			addCriterion("kanagra between", value1, value2, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraNotBetween(String value1, String value2) {
			addCriterion("kanagra not between", value1, value2, "kanagra");
			return (Criteria) this;
		}

		public Criteria andIstatprvresIsNull() {
			addCriterion("istatprvres is null");
			return (Criteria) this;
		}

		public Criteria andIstatprvresIsNotNull() {
			addCriterion("istatprvres is not null");
			return (Criteria) this;
		}

		public Criteria andIstatprvresEqualTo(String value) {
			addCriterion("istatprvres =", value, "istatprvres");
			return (Criteria) this;
		}

		public Criteria andIstatprvresNotEqualTo(String value) {
			addCriterion("istatprvres <>", value, "istatprvres");
			return (Criteria) this;
		}

		public Criteria andIstatprvresGreaterThan(String value) {
			addCriterion("istatprvres >", value, "istatprvres");
			return (Criteria) this;
		}

		public Criteria andIstatprvresGreaterThanOrEqualTo(String value) {
			addCriterion("istatprvres >=", value, "istatprvres");
			return (Criteria) this;
		}

		public Criteria andIstatprvresLessThan(String value) {
			addCriterion("istatprvres <", value, "istatprvres");
			return (Criteria) this;
		}

		public Criteria andIstatprvresLessThanOrEqualTo(String value) {
			addCriterion("istatprvres <=", value, "istatprvres");
			return (Criteria) this;
		}

		public Criteria andIstatprvresLike(String value) {
			addCriterion("istatprvres like", value, "istatprvres");
			return (Criteria) this;
		}

		public Criteria andIstatprvresNotLike(String value) {
			addCriterion("istatprvres not like", value, "istatprvres");
			return (Criteria) this;
		}

		public Criteria andIstatprvresIn(List<String> values) {
			addCriterion("istatprvres in", values, "istatprvres");
			return (Criteria) this;
		}

		public Criteria andIstatprvresNotIn(List<String> values) {
			addCriterion("istatprvres not in", values, "istatprvres");
			return (Criteria) this;
		}

		public Criteria andIstatprvresBetween(String value1, String value2) {
			addCriterion("istatprvres between", value1, value2, "istatprvres");
			return (Criteria) this;
		}

		public Criteria andIstatprvresNotBetween(String value1, String value2) {
			addCriterion("istatprvres not between", value1, value2, "istatprvres");
			return (Criteria) this;
		}

		public Criteria andIstatresIsNull() {
			addCriterion("istatres is null");
			return (Criteria) this;
		}

		public Criteria andIstatresIsNotNull() {
			addCriterion("istatres is not null");
			return (Criteria) this;
		}

		public Criteria andIstatresEqualTo(String value) {
			addCriterion("istatres =", value, "istatres");
			return (Criteria) this;
		}

		public Criteria andIstatresNotEqualTo(String value) {
			addCriterion("istatres <>", value, "istatres");
			return (Criteria) this;
		}

		public Criteria andIstatresGreaterThan(String value) {
			addCriterion("istatres >", value, "istatres");
			return (Criteria) this;
		}

		public Criteria andIstatresGreaterThanOrEqualTo(String value) {
			addCriterion("istatres >=", value, "istatres");
			return (Criteria) this;
		}

		public Criteria andIstatresLessThan(String value) {
			addCriterion("istatres <", value, "istatres");
			return (Criteria) this;
		}

		public Criteria andIstatresLessThanOrEqualTo(String value) {
			addCriterion("istatres <=", value, "istatres");
			return (Criteria) this;
		}

		public Criteria andIstatresLike(String value) {
			addCriterion("istatres like", value, "istatres");
			return (Criteria) this;
		}

		public Criteria andIstatresNotLike(String value) {
			addCriterion("istatres not like", value, "istatres");
			return (Criteria) this;
		}

		public Criteria andIstatresIn(List<String> values) {
			addCriterion("istatres in", values, "istatres");
			return (Criteria) this;
		}

		public Criteria andIstatresNotIn(List<String> values) {
			addCriterion("istatres not in", values, "istatres");
			return (Criteria) this;
		}

		public Criteria andIstatresBetween(String value1, String value2) {
			addCriterion("istatres between", value1, value2, "istatres");
			return (Criteria) this;
		}

		public Criteria andIstatresNotBetween(String value1, String value2) {
			addCriterion("istatres not between", value1, value2, "istatres");
			return (Criteria) this;
		}

		public Criteria andDatatimeinsIsNull() {
			addCriterion("datatimeins is null");
			return (Criteria) this;
		}

		public Criteria andDatatimeinsIsNotNull() {
			addCriterion("datatimeins is not null");
			return (Criteria) this;
		}

		public Criteria andDatatimeinsEqualTo(String value) {
			addCriterion("datatimeins =", value, "datatimeins");
			return (Criteria) this;
		}

		public Criteria andDatatimeinsNotEqualTo(String value) {
			addCriterion("datatimeins <>", value, "datatimeins");
			return (Criteria) this;
		}

		public Criteria andDatatimeinsGreaterThan(String value) {
			addCriterion("datatimeins >", value, "datatimeins");
			return (Criteria) this;
		}

		public Criteria andDatatimeinsGreaterThanOrEqualTo(String value) {
			addCriterion("datatimeins >=", value, "datatimeins");
			return (Criteria) this;
		}

		public Criteria andDatatimeinsLessThan(String value) {
			addCriterion("datatimeins <", value, "datatimeins");
			return (Criteria) this;
		}

		public Criteria andDatatimeinsLessThanOrEqualTo(String value) {
			addCriterion("datatimeins <=", value, "datatimeins");
			return (Criteria) this;
		}

		public Criteria andDatatimeinsLike(String value) {
			addCriterion("datatimeins like", value, "datatimeins");
			return (Criteria) this;
		}

		public Criteria andDatatimeinsNotLike(String value) {
			addCriterion("datatimeins not like", value, "datatimeins");
			return (Criteria) this;
		}

		public Criteria andDatatimeinsIn(List<String> values) {
			addCriterion("datatimeins in", values, "datatimeins");
			return (Criteria) this;
		}

		public Criteria andDatatimeinsNotIn(List<String> values) {
			addCriterion("datatimeins not in", values, "datatimeins");
			return (Criteria) this;
		}

		public Criteria andDatatimeinsBetween(String value1, String value2) {
			addCriterion("datatimeins between", value1, value2, "datatimeins");
			return (Criteria) this;
		}

		public Criteria andDatatimeinsNotBetween(String value1, String value2) {
			addCriterion("datatimeins not between", value1, value2, "datatimeins");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table parole
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table parole
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 18 09:27:24 CEST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}