package it.vidoc.mybatis.javamodel;

public class StrcodfiscKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strcodfisc.kanagra
	 * @mbggenerated
	 */
	private Long kanagra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strcodfisc.parola
	 * @mbggenerated
	 */
	private String parola;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strcodfisc.kanagra
	 * @return  the value of strcodfisc.kanagra
	 * @mbggenerated
	 */
	public Long getKanagra() {
		return kanagra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strcodfisc.kanagra
	 * @param kanagra  the value for strcodfisc.kanagra
	 * @mbggenerated
	 */
	public void setKanagra(Long kanagra) {
		this.kanagra = kanagra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strcodfisc.parola
	 * @return  the value of strcodfisc.parola
	 * @mbggenerated
	 */
	public String getParola() {
		return parola;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strcodfisc.parola
	 * @param parola  the value for strcodfisc.parola
	 * @mbggenerated
	 */
	public void setParola(String parola) {
		this.parola = parola;
	}
}