package it.vidoc.mybatis.javamodel;

public class Strnomi15 extends Strnomi15Key {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strnomi15.dateflusso
	 * @mbggenerated
	 */
	private String dateflusso;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strnomi15.datatimeins
	 * @mbggenerated
	 */
	private String datatimeins;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strnomi15.dateflusso
	 * @return  the value of strnomi15.dateflusso
	 * @mbggenerated
	 */
	public String getDateflusso() {
		return dateflusso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strnomi15.dateflusso
	 * @param dateflusso  the value for strnomi15.dateflusso
	 * @mbggenerated
	 */
	public void setDateflusso(String dateflusso) {
		this.dateflusso = dateflusso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strnomi15.datatimeins
	 * @return  the value of strnomi15.datatimeins
	 * @mbggenerated
	 */
	public String getDatatimeins() {
		return datatimeins;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strnomi15.datatimeins
	 * @param datatimeins  the value for strnomi15.datatimeins
	 * @mbggenerated
	 */
	public void setDatatimeins(String datatimeins) {
		this.datatimeins = datatimeins;
	}
}