package it.vidoc.mybatis.javamodel;

public class Strnomi08 extends Strnomi08Key {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strnomi08.dateflusso
	 * @mbggenerated
	 */
	private String dateflusso;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strnomi08.datatimeins
	 * @mbggenerated
	 */
	private String datatimeins;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strnomi08.dateflusso
	 * @return  the value of strnomi08.dateflusso
	 * @mbggenerated
	 */
	public String getDateflusso() {
		return dateflusso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strnomi08.dateflusso
	 * @param dateflusso  the value for strnomi08.dateflusso
	 * @mbggenerated
	 */
	public void setDateflusso(String dateflusso) {
		this.dateflusso = dateflusso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strnomi08.datatimeins
	 * @return  the value of strnomi08.datatimeins
	 * @mbggenerated
	 */
	public String getDatatimeins() {
		return datatimeins;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strnomi08.datatimeins
	 * @param datatimeins  the value for strnomi08.datatimeins
	 * @mbggenerated
	 */
	public void setDatatimeins(String datatimeins) {
		this.datatimeins = datatimeins;
	}
}