package it.vidoc.mybatis.javamodel;

public class Strnomi07Key {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strnomi07.kanagra
	 * @mbggenerated
	 */
	private Long kanagra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column strnomi07.parola
	 * @mbggenerated
	 */
	private String parola;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strnomi07.kanagra
	 * @return  the value of strnomi07.kanagra
	 * @mbggenerated
	 */
	public Long getKanagra() {
		return kanagra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strnomi07.kanagra
	 * @param kanagra  the value for strnomi07.kanagra
	 * @mbggenerated
	 */
	public void setKanagra(Long kanagra) {
		this.kanagra = kanagra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column strnomi07.parola
	 * @return  the value of strnomi07.parola
	 * @mbggenerated
	 */
	public String getParola() {
		return parola;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column strnomi07.parola
	 * @param parola  the value for strnomi07.parola
	 * @mbggenerated
	 */
	public void setParola(String parola) {
		this.parola = parola;
	}
}