package it.vidoc.mybatis.javamodel;

public class Userabilitazioni {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userabilitazioni.progrriga
	 * @mbggenerated
	 */
	private Integer progrriga;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userabilitazioni.username
	 * @mbggenerated
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userabilitazioni.abilitazione
	 * @mbggenerated
	 */
	private String abilitazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userabilitazioni.progrriga
	 * @return  the value of userabilitazioni.progrriga
	 * @mbggenerated
	 */
	public Integer getProgrriga() {
		return progrriga;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userabilitazioni.progrriga
	 * @param progrriga  the value for userabilitazioni.progrriga
	 * @mbggenerated
	 */
	public void setProgrriga(Integer progrriga) {
		this.progrriga = progrriga;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userabilitazioni.username
	 * @return  the value of userabilitazioni.username
	 * @mbggenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userabilitazioni.username
	 * @param username  the value for userabilitazioni.username
	 * @mbggenerated
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userabilitazioni.abilitazione
	 * @return  the value of userabilitazioni.abilitazione
	 * @mbggenerated
	 */
	public String getAbilitazione() {
		return abilitazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userabilitazioni.abilitazione
	 * @param abilitazione  the value for userabilitazioni.abilitazione
	 * @mbggenerated
	 */
	public void setAbilitazione(String abilitazione) {
		this.abilitazione = abilitazione;
	}
}