//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 05:59:41 PM CEST 
//


package it.vidoc.registro.imprese.ricerca.anagrafica.response;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnagraficaImpresaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnagraficaImpresaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cciaa" type="{}CciaaType" minOccurs="0"/>
 *         &lt;element name="DescCciaa" type="{}DescrizioneType" minOccurs="0"/>
 *         &lt;element name="NRea" type="{}NReaType" minOccurs="0"/>
 *         &lt;element name="Denominazione" type="{}DenominazioneType" minOccurs="0"/>
 *         &lt;element name="SglPrvSede" type="{}CciaaType" minOccurs="0"/>
 *         &lt;element name="DescPrvSede" type="{}DescrizioneType" minOccurs="0"/>
 *         &lt;element name="CodFisc" type="{}CodFiscType" minOccurs="0"/>
 *         &lt;element name="PIva" type="{}PIvaType" minOccurs="0"/>
 *         &lt;element name="NatGiu" type="{}NatGiuType" minOccurs="0"/>
 *         &lt;element name="DescNatGiu" type="{}DescrizioneType" minOccurs="0"/>
 *         &lt;element name="Fonte" type="{}FonteType" minOccurs="0"/>
 *         &lt;element name="DescFonte" type="{}DescrizioneType" minOccurs="0"/>
 *         &lt;element name="StatoAttivita" type="{}StatoAttivitaType" minOccurs="0"/>
 *         &lt;element name="DescStatoAttivita" type="{}DescrizioneType" minOccurs="0"/>
 *         &lt;element name="CodAttivitaAteco" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DescAttivitaAteco" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClassificazioneAteco" type="{}ClassificazioneAtecoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IndirizzoSede" type="{}IndirizzoSedeType" minOccurs="0"/>
 *         &lt;element name="IndirizzoLocalizzazione" type="{}IndirizzoLocalizzazioneType" minOccurs="0"/>
 *         &lt;element name="IndirizzoPostaCertificata" type="{}IndirizzoPostaCertificataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnagraficaImpresaType", propOrder = {
    "content"
})
public class AnagraficaImpresaType {

    @XmlElementRefs({
        @XmlElementRef(name = "IndirizzoSede", type = JAXBElement.class),
        @XmlElementRef(name = "Cciaa", type = JAXBElement.class),
        @XmlElementRef(name = "Fonte", type = JAXBElement.class),
        @XmlElementRef(name = "CodAttivitaAteco", type = JAXBElement.class),
        @XmlElementRef(name = "IndirizzoPostaCertificata", type = JAXBElement.class),
        @XmlElementRef(name = "PIva", type = JAXBElement.class),
        @XmlElementRef(name = "DescFonte", type = JAXBElement.class),
        @XmlElementRef(name = "NRea", type = JAXBElement.class),
        @XmlElementRef(name = "DescNatGiu", type = JAXBElement.class),
        @XmlElementRef(name = "NatGiu", type = JAXBElement.class),
        @XmlElementRef(name = "CodFisc", type = JAXBElement.class),
        @XmlElementRef(name = "SglPrvSede", type = JAXBElement.class),
        @XmlElementRef(name = "DescPrvSede", type = JAXBElement.class),
        @XmlElementRef(name = "Denominazione", type = JAXBElement.class),
        @XmlElementRef(name = "DescCciaa", type = JAXBElement.class),
        @XmlElementRef(name = "ClassificazioneAteco", type = JAXBElement.class),
        @XmlElementRef(name = "DescStatoAttivita", type = JAXBElement.class),
        @XmlElementRef(name = "StatoAttivita", type = JAXBElement.class),
        @XmlElementRef(name = "DescAttivitaAteco", type = JAXBElement.class),
        @XmlElementRef(name = "IndirizzoLocalizzazione", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link IndirizzoSedeType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link FonteType }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link IndirizzoPostaCertificataType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ClassificazioneAtecoType }{@code >}
     * {@link JAXBElement }{@code <}{@link StatoAttivitaType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link IndirizzoLocalizzazioneType }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}
