//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 05:59:41 PM CEST 
//


package it.vidoc.registro.imprese.ricerca.anagrafica.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IndirizzoSedeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndirizzoSedeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SglPrvSede" type="{}CciaaType" minOccurs="0"/>
 *         &lt;element name="DescPrvSede" type="{}DescrizioneType" minOccurs="0"/>
 *         &lt;element name="CodComSede" type="{}CodComType" minOccurs="0"/>
 *         &lt;element name="DescComSede" type="{}DescrizioneType" minOccurs="0"/>
 *         &lt;element name="CodToponSede" type="{}CodToponType" minOccurs="0"/>
 *         &lt;element name="DescToponSede" type="{}DescrizioneType" minOccurs="0"/>
 *         &lt;element name="ViaSede" type="{}ViaType" minOccurs="0"/>
 *         &lt;element name="NCivicoSede" type="{}NCivicoType" minOccurs="0"/>
 *         &lt;element name="CapSede" type="{}CapType" minOccurs="0"/>
 *         &lt;element name="FrazioneSede" type="{}FrazioneType" minOccurs="0"/>
 *         &lt;element name="CodStatoEstero" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DescStatoEstero" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndirizzoSedeType", propOrder = {
    "sglPrvSede",
    "descPrvSede",
    "codComSede",
    "descComSede",
    "codToponSede",
    "descToponSede",
    "viaSede",
    "nCivicoSede",
    "capSede",
    "frazioneSede",
    "codStatoEstero",
    "descStatoEstero"
})
public class IndirizzoSedeType {

    @XmlElement(name = "SglPrvSede")
    protected String sglPrvSede;
    @XmlElement(name = "DescPrvSede")
    protected String descPrvSede;
    @XmlElement(name = "CodComSede")
    protected String codComSede;
    @XmlElement(name = "DescComSede")
    protected String descComSede;
    @XmlElement(name = "CodToponSede")
    protected String codToponSede;
    @XmlElement(name = "DescToponSede")
    protected String descToponSede;
    @XmlElement(name = "ViaSede")
    protected String viaSede;
    @XmlElement(name = "NCivicoSede")
    protected String nCivicoSede;
    @XmlElement(name = "CapSede")
    protected String capSede;
    @XmlElement(name = "FrazioneSede")
    protected String frazioneSede;
    @XmlElement(name = "CodStatoEstero")
    protected String codStatoEstero;
    @XmlElement(name = "DescStatoEstero")
    protected String descStatoEstero;

    /**
     * Gets the value of the sglPrvSede property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSglPrvSede() {
        return sglPrvSede;
    }

    /**
     * Sets the value of the sglPrvSede property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSglPrvSede(String value) {
        this.sglPrvSede = value;
    }

    /**
     * Gets the value of the descPrvSede property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescPrvSede() {
        return descPrvSede;
    }

    /**
     * Sets the value of the descPrvSede property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescPrvSede(String value) {
        this.descPrvSede = value;
    }

    /**
     * Gets the value of the codComSede property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodComSede() {
        return codComSede;
    }

    /**
     * Sets the value of the codComSede property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodComSede(String value) {
        this.codComSede = value;
    }

    /**
     * Gets the value of the descComSede property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescComSede() {
        return descComSede;
    }

    /**
     * Sets the value of the descComSede property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescComSede(String value) {
        this.descComSede = value;
    }

    /**
     * Gets the value of the codToponSede property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodToponSede() {
        return codToponSede;
    }

    /**
     * Sets the value of the codToponSede property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodToponSede(String value) {
        this.codToponSede = value;
    }

    /**
     * Gets the value of the descToponSede property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescToponSede() {
        return descToponSede;
    }

    /**
     * Sets the value of the descToponSede property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescToponSede(String value) {
        this.descToponSede = value;
    }

    /**
     * Gets the value of the viaSede property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViaSede() {
        return viaSede;
    }

    /**
     * Sets the value of the viaSede property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViaSede(String value) {
        this.viaSede = value;
    }

    /**
     * Gets the value of the nCivicoSede property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNCivicoSede() {
        return nCivicoSede;
    }

    /**
     * Sets the value of the nCivicoSede property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNCivicoSede(String value) {
        this.nCivicoSede = value;
    }

    /**
     * Gets the value of the capSede property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapSede() {
        return capSede;
    }

    /**
     * Sets the value of the capSede property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapSede(String value) {
        this.capSede = value;
    }

    /**
     * Gets the value of the frazioneSede property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrazioneSede() {
        return frazioneSede;
    }

    /**
     * Sets the value of the frazioneSede property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrazioneSede(String value) {
        this.frazioneSede = value;
    }

    /**
     * Gets the value of the codStatoEstero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodStatoEstero() {
        return codStatoEstero;
    }

    /**
     * Sets the value of the codStatoEstero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodStatoEstero(String value) {
        this.codStatoEstero = value;
    }

    /**
     * Gets the value of the descStatoEstero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescStatoEstero() {
        return descStatoEstero;
    }

    /**
     * Sets the value of the descStatoEstero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescStatoEstero(String value) {
        this.descStatoEstero = value;
    }

}
