//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 05:59:41 PM CEST 
//


package it.vidoc.registro.imprese.ricerca.anagrafica.response;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.vidoc.registro.imprese.response.ricerca.anagrafica package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AnagraficaPersonaGiuridicaTypeDescPrimaCarica_QNAME = new QName("", "DescPrimaCarica");
    private final static QName _AnagraficaPersonaGiuridicaTypeNReaSocPar_QNAME = new QName("", "NReaSocPar");
    private final static QName _AnagraficaPersonaGiuridicaTypeCodFiscPers_QNAME = new QName("", "CodFiscPers");
    private final static QName _AnagraficaPersonaGiuridicaTypeDenomSocPar_QNAME = new QName("", "DenomSocPar");
    private final static QName _AnagraficaPersonaGiuridicaTypeCciaaSocPar_QNAME = new QName("", "CciaaSocPar");
    private final static QName _AnagraficaPersonaGiuridicaTypeDtCostituzSocPar_QNAME = new QName("", "DtCostituzSocPar");
    private final static QName _AnagraficaPersonaGiuridicaTypeCodPrimaCarica_QNAME = new QName("", "CodPrimaCarica");
    private final static QName _ListaImpreseRI_QNAME = new QName("", "ListaImpreseRI");
    private final static QName _Messaggio_QNAME = new QName("", "Messaggio");
    private final static QName _Testata_QNAME = new QName("", "Testata");
    private final static QName _ImpresaTypeAnagraficaPersona_QNAME = new QName("", "AnagraficaPersona");
    private final static QName _ImpresaTypeProgressivoImpresa_QNAME = new QName("", "ProgressivoImpresa");
    private final static QName _ImpresaTypeAnagraficaPersonaGiuridica_QNAME = new QName("", "AnagraficaPersonaGiuridica");
    private final static QName _ImpresaTypeAnagraficaImpresa_QNAME = new QName("", "AnagraficaImpresa");
    private final static QName _AnagraficaImpresaTypeCodFisc_QNAME = new QName("", "CodFisc");
    private final static QName _AnagraficaImpresaTypeDescAttivitaAteco_QNAME = new QName("", "DescAttivitaAteco");
    private final static QName _AnagraficaImpresaTypeDescNatGiu_QNAME = new QName("", "DescNatGiu");
    private final static QName _AnagraficaImpresaTypeIndirizzoSede_QNAME = new QName("", "IndirizzoSede");
    private final static QName _AnagraficaImpresaTypePIva_QNAME = new QName("", "PIva");
    private final static QName _AnagraficaImpresaTypeIndirizzoPostaCertificata_QNAME = new QName("", "IndirizzoPostaCertificata");
    private final static QName _AnagraficaImpresaTypeDescPrvSede_QNAME = new QName("", "DescPrvSede");
    private final static QName _AnagraficaImpresaTypeDenominazione_QNAME = new QName("", "Denominazione");
    private final static QName _AnagraficaImpresaTypeStatoAttivita_QNAME = new QName("", "StatoAttivita");
    private final static QName _AnagraficaImpresaTypeFonte_QNAME = new QName("", "Fonte");
    private final static QName _AnagraficaImpresaTypeNRea_QNAME = new QName("", "NRea");
    private final static QName _AnagraficaImpresaTypeDescStatoAttivita_QNAME = new QName("", "DescStatoAttivita");
    private final static QName _AnagraficaImpresaTypeDescCciaa_QNAME = new QName("", "DescCciaa");
    private final static QName _AnagraficaImpresaTypeDescFonte_QNAME = new QName("", "DescFonte");
    private final static QName _AnagraficaImpresaTypeIndirizzoLocalizzazione_QNAME = new QName("", "IndirizzoLocalizzazione");
    private final static QName _AnagraficaImpresaTypeSglPrvSede_QNAME = new QName("", "SglPrvSede");
    private final static QName _AnagraficaImpresaTypeNatGiu_QNAME = new QName("", "NatGiu");
    private final static QName _AnagraficaImpresaTypeCciaa_QNAME = new QName("", "Cciaa");
    private final static QName _AnagraficaImpresaTypeCodAttivitaAteco_QNAME = new QName("", "CodAttivitaAteco");
    private final static QName _AnagraficaImpresaTypeClassificazioneAteco_QNAME = new QName("", "ClassificazioneAteco");
    private final static QName _AnagraficaPersonaTypeSglPrvNas_QNAME = new QName("", "SglPrvNas");
    private final static QName _AnagraficaPersonaTypeSesso_QNAME = new QName("", "Sesso");
    private final static QName _AnagraficaPersonaTypeCodStaNas_QNAME = new QName("", "CodStaNas");
    private final static QName _AnagraficaPersonaTypeDescStaNas_QNAME = new QName("", "DescStaNas");
    private final static QName _AnagraficaPersonaTypeDtNascita_QNAME = new QName("", "DtNascita");
    private final static QName _AnagraficaPersonaTypeDescPrvNas_QNAME = new QName("", "DescPrvNas");
    private final static QName _AnagraficaPersonaTypeCognome_QNAME = new QName("", "Cognome");
    private final static QName _AnagraficaPersonaTypeLuogoNas_QNAME = new QName("", "LuogoNas");
    private final static QName _AnagraficaPersonaTypeNome_QNAME = new QName("", "Nome");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.vidoc.registro.imprese.response.ricerca.anagrafica
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IndirizzoPostaCertificataType }
     * 
     */
    public IndirizzoPostaCertificataType createIndirizzoPostaCertificataType() {
        return new IndirizzoPostaCertificataType();
    }

    /**
     * Create an instance of {@link IndirizzoSedeType }
     * 
     */
    public IndirizzoSedeType createIndirizzoSedeType() {
        return new IndirizzoSedeType();
    }

    /**
     * Create an instance of {@link IndirizzoLocalizzazioneType }
     * 
     */
    public IndirizzoLocalizzazioneType createIndirizzoLocalizzazioneType() {
        return new IndirizzoLocalizzazioneType();
    }

    /**
     * Create an instance of {@link Risposta }
     * 
     */
    public Risposta createRisposta() {
        return new Risposta();
    }

    /**
     * Create an instance of {@link ListaImpreseRIType }
     * 
     */
    public ListaImpreseRIType createListaImpreseRIType() {
        return new ListaImpreseRIType();
    }

    /**
     * Create an instance of {@link ImpresaType }
     * 
     */
    public ImpresaType createImpresaType() {
        return new ImpresaType();
    }

    /**
     * Create an instance of {@link TestataType }
     * 
     */
    public TestataType createTestataType() {
        return new TestataType();
    }

    /**
     * Create an instance of {@link ClassificazioneAtecoType }
     * 
     */
    public ClassificazioneAtecoType createClassificazioneAtecoType() {
        return new ClassificazioneAtecoType();
    }

    /**
     * Create an instance of {@link AnagraficaPersonaType }
     * 
     */
    public AnagraficaPersonaType createAnagraficaPersonaType() {
        return new AnagraficaPersonaType();
    }

    /**
     * Create an instance of {@link AnagraficaPersonaGiuridicaType }
     * 
     */
    public AnagraficaPersonaGiuridicaType createAnagraficaPersonaGiuridicaType() {
        return new AnagraficaPersonaGiuridicaType();
    }

    /**
     * Create an instance of {@link RiepilogoType }
     * 
     */
    public RiepilogoType createRiepilogoType() {
        return new RiepilogoType();
    }

    /**
     * Create an instance of {@link MessaggioType }
     * 
     */
    public MessaggioType createMessaggioType() {
        return new MessaggioType();
    }

    /**
     * Create an instance of {@link AnagraficaImpresaType }
     * 
     */
    public AnagraficaImpresaType createAnagraficaImpresaType() {
        return new AnagraficaImpresaType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DescPrimaCarica", scope = AnagraficaPersonaGiuridicaType.class)
    public JAXBElement<String> createAnagraficaPersonaGiuridicaTypeDescPrimaCarica(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaGiuridicaTypeDescPrimaCarica_QNAME, String.class, AnagraficaPersonaGiuridicaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NReaSocPar", scope = AnagraficaPersonaGiuridicaType.class)
    public JAXBElement<BigInteger> createAnagraficaPersonaGiuridicaTypeNReaSocPar(BigInteger value) {
        return new JAXBElement<BigInteger>(_AnagraficaPersonaGiuridicaTypeNReaSocPar_QNAME, BigInteger.class, AnagraficaPersonaGiuridicaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodFiscPers", scope = AnagraficaPersonaGiuridicaType.class)
    public JAXBElement<String> createAnagraficaPersonaGiuridicaTypeCodFiscPers(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaGiuridicaTypeCodFiscPers_QNAME, String.class, AnagraficaPersonaGiuridicaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DenomSocPar", scope = AnagraficaPersonaGiuridicaType.class)
    public JAXBElement<String> createAnagraficaPersonaGiuridicaTypeDenomSocPar(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaGiuridicaTypeDenomSocPar_QNAME, String.class, AnagraficaPersonaGiuridicaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CciaaSocPar", scope = AnagraficaPersonaGiuridicaType.class)
    public JAXBElement<String> createAnagraficaPersonaGiuridicaTypeCciaaSocPar(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaGiuridicaTypeCciaaSocPar_QNAME, String.class, AnagraficaPersonaGiuridicaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DtCostituzSocPar", scope = AnagraficaPersonaGiuridicaType.class)
    public JAXBElement<XMLGregorianCalendar> createAnagraficaPersonaGiuridicaTypeDtCostituzSocPar(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AnagraficaPersonaGiuridicaTypeDtCostituzSocPar_QNAME, XMLGregorianCalendar.class, AnagraficaPersonaGiuridicaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodPrimaCarica", scope = AnagraficaPersonaGiuridicaType.class)
    public JAXBElement<String> createAnagraficaPersonaGiuridicaTypeCodPrimaCarica(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaGiuridicaTypeCodPrimaCarica_QNAME, String.class, AnagraficaPersonaGiuridicaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListaImpreseRIType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ListaImpreseRI")
    public JAXBElement<ListaImpreseRIType> createListaImpreseRI(ListaImpreseRIType value) {
        return new JAXBElement<ListaImpreseRIType>(_ListaImpreseRI_QNAME, ListaImpreseRIType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessaggioType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Messaggio")
    public JAXBElement<MessaggioType> createMessaggio(MessaggioType value) {
        return new JAXBElement<MessaggioType>(_Messaggio_QNAME, MessaggioType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Testata")
    public JAXBElement<TestataType> createTestata(TestataType value) {
        return new JAXBElement<TestataType>(_Testata_QNAME, TestataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnagraficaPersonaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AnagraficaPersona", scope = ImpresaType.class)
    public JAXBElement<AnagraficaPersonaType> createImpresaTypeAnagraficaPersona(AnagraficaPersonaType value) {
        return new JAXBElement<AnagraficaPersonaType>(_ImpresaTypeAnagraficaPersona_QNAME, AnagraficaPersonaType.class, ImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProgressivoImpresa", scope = ImpresaType.class)
    public JAXBElement<BigInteger> createImpresaTypeProgressivoImpresa(BigInteger value) {
        return new JAXBElement<BigInteger>(_ImpresaTypeProgressivoImpresa_QNAME, BigInteger.class, ImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnagraficaPersonaGiuridicaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AnagraficaPersonaGiuridica", scope = ImpresaType.class)
    public JAXBElement<AnagraficaPersonaGiuridicaType> createImpresaTypeAnagraficaPersonaGiuridica(AnagraficaPersonaGiuridicaType value) {
        return new JAXBElement<AnagraficaPersonaGiuridicaType>(_ImpresaTypeAnagraficaPersonaGiuridica_QNAME, AnagraficaPersonaGiuridicaType.class, ImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnagraficaImpresaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AnagraficaImpresa", scope = ImpresaType.class)
    public JAXBElement<AnagraficaImpresaType> createImpresaTypeAnagraficaImpresa(AnagraficaImpresaType value) {
        return new JAXBElement<AnagraficaImpresaType>(_ImpresaTypeAnagraficaImpresa_QNAME, AnagraficaImpresaType.class, ImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodFisc", scope = AnagraficaImpresaType.class)
    public JAXBElement<String> createAnagraficaImpresaTypeCodFisc(String value) {
        return new JAXBElement<String>(_AnagraficaImpresaTypeCodFisc_QNAME, String.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DescAttivitaAteco", scope = AnagraficaImpresaType.class)
    public JAXBElement<String> createAnagraficaImpresaTypeDescAttivitaAteco(String value) {
        return new JAXBElement<String>(_AnagraficaImpresaTypeDescAttivitaAteco_QNAME, String.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DescNatGiu", scope = AnagraficaImpresaType.class)
    public JAXBElement<String> createAnagraficaImpresaTypeDescNatGiu(String value) {
        return new JAXBElement<String>(_AnagraficaImpresaTypeDescNatGiu_QNAME, String.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndirizzoSedeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IndirizzoSede", scope = AnagraficaImpresaType.class)
    public JAXBElement<IndirizzoSedeType> createAnagraficaImpresaTypeIndirizzoSede(IndirizzoSedeType value) {
        return new JAXBElement<IndirizzoSedeType>(_AnagraficaImpresaTypeIndirizzoSede_QNAME, IndirizzoSedeType.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PIva", scope = AnagraficaImpresaType.class)
    public JAXBElement<String> createAnagraficaImpresaTypePIva(String value) {
        return new JAXBElement<String>(_AnagraficaImpresaTypePIva_QNAME, String.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndirizzoPostaCertificataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IndirizzoPostaCertificata", scope = AnagraficaImpresaType.class)
    public JAXBElement<IndirizzoPostaCertificataType> createAnagraficaImpresaTypeIndirizzoPostaCertificata(IndirizzoPostaCertificataType value) {
        return new JAXBElement<IndirizzoPostaCertificataType>(_AnagraficaImpresaTypeIndirizzoPostaCertificata_QNAME, IndirizzoPostaCertificataType.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DescPrvSede", scope = AnagraficaImpresaType.class)
    public JAXBElement<String> createAnagraficaImpresaTypeDescPrvSede(String value) {
        return new JAXBElement<String>(_AnagraficaImpresaTypeDescPrvSede_QNAME, String.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Denominazione", scope = AnagraficaImpresaType.class)
    public JAXBElement<String> createAnagraficaImpresaTypeDenominazione(String value) {
        return new JAXBElement<String>(_AnagraficaImpresaTypeDenominazione_QNAME, String.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatoAttivitaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StatoAttivita", scope = AnagraficaImpresaType.class)
    public JAXBElement<StatoAttivitaType> createAnagraficaImpresaTypeStatoAttivita(StatoAttivitaType value) {
        return new JAXBElement<StatoAttivitaType>(_AnagraficaImpresaTypeStatoAttivita_QNAME, StatoAttivitaType.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FonteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Fonte", scope = AnagraficaImpresaType.class)
    public JAXBElement<FonteType> createAnagraficaImpresaTypeFonte(FonteType value) {
        return new JAXBElement<FonteType>(_AnagraficaImpresaTypeFonte_QNAME, FonteType.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NRea", scope = AnagraficaImpresaType.class)
    public JAXBElement<BigInteger> createAnagraficaImpresaTypeNRea(BigInteger value) {
        return new JAXBElement<BigInteger>(_AnagraficaImpresaTypeNRea_QNAME, BigInteger.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DescStatoAttivita", scope = AnagraficaImpresaType.class)
    public JAXBElement<String> createAnagraficaImpresaTypeDescStatoAttivita(String value) {
        return new JAXBElement<String>(_AnagraficaImpresaTypeDescStatoAttivita_QNAME, String.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DescCciaa", scope = AnagraficaImpresaType.class)
    public JAXBElement<String> createAnagraficaImpresaTypeDescCciaa(String value) {
        return new JAXBElement<String>(_AnagraficaImpresaTypeDescCciaa_QNAME, String.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DescFonte", scope = AnagraficaImpresaType.class)
    public JAXBElement<String> createAnagraficaImpresaTypeDescFonte(String value) {
        return new JAXBElement<String>(_AnagraficaImpresaTypeDescFonte_QNAME, String.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndirizzoLocalizzazioneType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IndirizzoLocalizzazione", scope = AnagraficaImpresaType.class)
    public JAXBElement<IndirizzoLocalizzazioneType> createAnagraficaImpresaTypeIndirizzoLocalizzazione(IndirizzoLocalizzazioneType value) {
        return new JAXBElement<IndirizzoLocalizzazioneType>(_AnagraficaImpresaTypeIndirizzoLocalizzazione_QNAME, IndirizzoLocalizzazioneType.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SglPrvSede", scope = AnagraficaImpresaType.class)
    public JAXBElement<String> createAnagraficaImpresaTypeSglPrvSede(String value) {
        return new JAXBElement<String>(_AnagraficaImpresaTypeSglPrvSede_QNAME, String.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NatGiu", scope = AnagraficaImpresaType.class)
    public JAXBElement<String> createAnagraficaImpresaTypeNatGiu(String value) {
        return new JAXBElement<String>(_AnagraficaImpresaTypeNatGiu_QNAME, String.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cciaa", scope = AnagraficaImpresaType.class)
    public JAXBElement<String> createAnagraficaImpresaTypeCciaa(String value) {
        return new JAXBElement<String>(_AnagraficaImpresaTypeCciaa_QNAME, String.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodAttivitaAteco", scope = AnagraficaImpresaType.class)
    public JAXBElement<String> createAnagraficaImpresaTypeCodAttivitaAteco(String value) {
        return new JAXBElement<String>(_AnagraficaImpresaTypeCodAttivitaAteco_QNAME, String.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassificazioneAtecoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ClassificazioneAteco", scope = AnagraficaImpresaType.class)
    public JAXBElement<ClassificazioneAtecoType> createAnagraficaImpresaTypeClassificazioneAteco(ClassificazioneAtecoType value) {
        return new JAXBElement<ClassificazioneAtecoType>(_AnagraficaImpresaTypeClassificazioneAteco_QNAME, ClassificazioneAtecoType.class, AnagraficaImpresaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SglPrvNas", scope = AnagraficaPersonaType.class)
    public JAXBElement<String> createAnagraficaPersonaTypeSglPrvNas(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaTypeSglPrvNas_QNAME, String.class, AnagraficaPersonaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sesso", scope = AnagraficaPersonaType.class)
    public JAXBElement<String> createAnagraficaPersonaTypeSesso(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaTypeSesso_QNAME, String.class, AnagraficaPersonaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DescPrimaCarica", scope = AnagraficaPersonaType.class)
    public JAXBElement<String> createAnagraficaPersonaTypeDescPrimaCarica(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaGiuridicaTypeDescPrimaCarica_QNAME, String.class, AnagraficaPersonaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodStaNas", scope = AnagraficaPersonaType.class)
    public JAXBElement<String> createAnagraficaPersonaTypeCodStaNas(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaTypeCodStaNas_QNAME, String.class, AnagraficaPersonaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DescStaNas", scope = AnagraficaPersonaType.class)
    public JAXBElement<String> createAnagraficaPersonaTypeDescStaNas(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaTypeDescStaNas_QNAME, String.class, AnagraficaPersonaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodFiscPers", scope = AnagraficaPersonaType.class)
    public JAXBElement<String> createAnagraficaPersonaTypeCodFiscPers(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaGiuridicaTypeCodFiscPers_QNAME, String.class, AnagraficaPersonaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DtNascita", scope = AnagraficaPersonaType.class)
    public JAXBElement<XMLGregorianCalendar> createAnagraficaPersonaTypeDtNascita(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AnagraficaPersonaTypeDtNascita_QNAME, XMLGregorianCalendar.class, AnagraficaPersonaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DescPrvNas", scope = AnagraficaPersonaType.class)
    public JAXBElement<String> createAnagraficaPersonaTypeDescPrvNas(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaTypeDescPrvNas_QNAME, String.class, AnagraficaPersonaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cognome", scope = AnagraficaPersonaType.class)
    public JAXBElement<String> createAnagraficaPersonaTypeCognome(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaTypeCognome_QNAME, String.class, AnagraficaPersonaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LuogoNas", scope = AnagraficaPersonaType.class)
    public JAXBElement<String> createAnagraficaPersonaTypeLuogoNas(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaTypeLuogoNas_QNAME, String.class, AnagraficaPersonaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Nome", scope = AnagraficaPersonaType.class)
    public JAXBElement<String> createAnagraficaPersonaTypeNome(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaTypeNome_QNAME, String.class, AnagraficaPersonaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodPrimaCarica", scope = AnagraficaPersonaType.class)
    public JAXBElement<String> createAnagraficaPersonaTypeCodPrimaCarica(String value) {
        return new JAXBElement<String>(_AnagraficaPersonaGiuridicaTypeCodPrimaCarica_QNAME, String.class, AnagraficaPersonaType.class, value);
    }

}
