//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.27 at 11:18:10 AM CEST 
//


package it.vidoc.registro.protesti.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListaAnagraficheProtestiType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListaAnagraficheProtestiType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="PerNominativoNazionaleOProvinciale" type="{}PerNominativoNazionaleOProvincialeType"/>
 *         &lt;element name="PerNominativoSuProvincie" type="{}PerNominativoSuProvincieType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListaAnagraficheProtestiType", propOrder = {
    "perNominativoNazionaleOProvinciale",
    "perNominativoSuProvincie"
})
public class ListaAnagraficheProtestiType {

    @XmlElement(name = "PerNominativoNazionaleOProvinciale")
    protected PerNominativoNazionaleOProvincialeType perNominativoNazionaleOProvinciale;
    @XmlElement(name = "PerNominativoSuProvincie")
    protected PerNominativoSuProvincieType perNominativoSuProvincie;

    /**
     * Gets the value of the perNominativoNazionaleOProvinciale property.
     * 
     * @return
     *     possible object is
     *     {@link PerNominativoNazionaleOProvincialeType }
     *     
     */
    public PerNominativoNazionaleOProvincialeType getPerNominativoNazionaleOProvinciale() {
        return perNominativoNazionaleOProvinciale;
    }

    /**
     * Sets the value of the perNominativoNazionaleOProvinciale property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerNominativoNazionaleOProvincialeType }
     *     
     */
    public void setPerNominativoNazionaleOProvinciale(PerNominativoNazionaleOProvincialeType value) {
        this.perNominativoNazionaleOProvinciale = value;
    }

    /**
     * Gets the value of the perNominativoSuProvincie property.
     * 
     * @return
     *     possible object is
     *     {@link PerNominativoSuProvincieType }
     *     
     */
    public PerNominativoSuProvincieType getPerNominativoSuProvincie() {
        return perNominativoSuProvincie;
    }

    /**
     * Sets the value of the perNominativoSuProvincie property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerNominativoSuProvincieType }
     *     
     */
    public void setPerNominativoSuProvincie(PerNominativoSuProvincieType value) {
        this.perNominativoSuProvincie = value;
    }

}
