//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.27 at 11:18:10 AM CEST 
//


package it.vidoc.registro.protesti.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PerNominativoNazionaleOProvincialeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PerNominativoNazionaleOProvincialeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParolaNominativo" type="{}ParolaNominativoType" maxOccurs="4"/>
 *         &lt;element name="SglPrvRes" type="{}CciaaType" minOccurs="0"/>
 *         &lt;element name="CodComRes" type="{}CodComType" minOccurs="0"/>
 *         &lt;element name="ParolaIndirizzoRes" type="{}ParolaIndirizzoType" maxOccurs="3" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PerNominativoNazionaleOProvincialeType", propOrder = {
    "parolaNominativo",
    "sglPrvRes",
    "codComRes",
    "parolaIndirizzoRes"
})
public class PerNominativoNazionaleOProvincialeType {

    @XmlElement(name = "ParolaNominativo", required = true)
    protected List<String> parolaNominativo;
    @XmlElement(name = "SglPrvRes")
    protected String sglPrvRes;
    @XmlElement(name = "CodComRes")
    protected String codComRes;
    @XmlElement(name = "ParolaIndirizzoRes", required = true)
    protected List<String> parolaIndirizzoRes;

    /**
     * Gets the value of the parolaNominativo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parolaNominativo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParolaNominativo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getParolaNominativo() {
        if (parolaNominativo == null) {
            parolaNominativo = new ArrayList<String>();
        }
        return this.parolaNominativo;
    }

    /**
     * Gets the value of the sglPrvRes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSglPrvRes() {
        return sglPrvRes;
    }

    /**
     * Sets the value of the sglPrvRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSglPrvRes(String value) {
        this.sglPrvRes = value;
    }

    /**
     * Gets the value of the codComRes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodComRes() {
        return codComRes;
    }

    /**
     * Sets the value of the codComRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodComRes(String value) {
        this.codComRes = value;
    }

    /**
     * Gets the value of the parolaIndirizzoRes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parolaIndirizzoRes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParolaIndirizzoRes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getParolaIndirizzoRes() {
        if (parolaIndirizzoRes == null) {
            parolaIndirizzoRes = new ArrayList<String>();
        }
        return this.parolaIndirizzoRes;
    }

}
