//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anagrafica-titolare element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="anagrafica-titolare">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="c-cittadinanza" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-fiscale" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-tipo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="cittadinanza" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="cognome" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="denominazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="denominazione-denunciata" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="dt-cancellazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="f-cessata" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="nome" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "anagrafica-titolare")
public class AnagraficaTitolare {

    @XmlAttribute(name = "c-cittadinanza")
    protected String cCittadinanza;
    @XmlAttribute(name = "c-fiscale")
    protected String cFiscale;
    @XmlAttribute(name = "c-tipo")
    protected String cTipo;
    @XmlAttribute
    protected String cittadinanza;
    @XmlAttribute
    protected String cognome;
    @XmlAttribute
    protected String denominazione;
    @XmlAttribute(name = "denominazione-denunciata")
    protected String denominazioneDenunciata;
    @XmlAttribute(name = "dt-cancellazione")
    protected String dtCancellazione;
    @XmlAttribute(name = "f-cessata")
    protected String fCessata;
    @XmlAttribute
    protected String nome;
    @XmlAttribute
    protected String tipo;

    /**
     * Gets the value of the cCittadinanza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCittadinanza() {
        return cCittadinanza;
    }

    /**
     * Sets the value of the cCittadinanza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCittadinanza(String value) {
        this.cCittadinanza = value;
    }

    /**
     * Gets the value of the cFiscale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCFiscale() {
        return cFiscale;
    }

    /**
     * Sets the value of the cFiscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCFiscale(String value) {
        this.cFiscale = value;
    }

    /**
     * Gets the value of the cTipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTipo() {
        return cTipo;
    }

    /**
     * Sets the value of the cTipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTipo(String value) {
        this.cTipo = value;
    }

    /**
     * Gets the value of the cittadinanza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCittadinanza() {
        return cittadinanza;
    }

    /**
     * Sets the value of the cittadinanza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCittadinanza(String value) {
        this.cittadinanza = value;
    }

    /**
     * Gets the value of the cognome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCognome() {
        return cognome;
    }

    /**
     * Sets the value of the cognome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCognome(String value) {
        this.cognome = value;
    }

    /**
     * Gets the value of the denominazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominazione() {
        return denominazione;
    }

    /**
     * Sets the value of the denominazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominazione(String value) {
        this.denominazione = value;
    }

    /**
     * Gets the value of the denominazioneDenunciata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominazioneDenunciata() {
        return denominazioneDenunciata;
    }

    /**
     * Sets the value of the denominazioneDenunciata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominazioneDenunciata(String value) {
        this.denominazioneDenunciata = value;
    }

    /**
     * Gets the value of the dtCancellazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtCancellazione() {
        return dtCancellazione;
    }

    /**
     * Sets the value of the dtCancellazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtCancellazione(String value) {
        this.dtCancellazione = value;
    }

    /**
     * Gets the value of the fCessata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFCessata() {
        return fCessata;
    }

    /**
     * Sets the value of the fCessata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFCessata(String value) {
        this.fCessata = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

}
