//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for attivita-no-aa element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="attivita-no-aa">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}descrizione" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}informazioni-supplementari-aa" minOccurs="0"/>
 *           &lt;element ref="{}cancellazione-aa" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="c-categoria" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="categoria" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="dt-inizio" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "descrizione",
    "informazioniSupplementariAa",
    "cancellazioneAa"
})
@XmlRootElement(name = "attivita-no-aa")
public class AttivitaNoAa {

    @XmlElement(required = true)
    protected List<String> descrizione;
    @XmlElement(name = "informazioni-supplementari-aa")
    protected String informazioniSupplementariAa;
    @XmlElement(name = "cancellazione-aa")
    protected CancellazioneAa cancellazioneAa;
    @XmlAttribute(name = "c-categoria")
    protected String cCategoria;
    @XmlAttribute
    protected String categoria;
    @XmlAttribute(name = "dt-inizio")
    protected String dtInizio;

    /**
     * Gets the value of the descrizione property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descrizione property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescrizione().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDescrizione() {
        if (descrizione == null) {
            descrizione = new ArrayList<String>();
        }
        return this.descrizione;
    }

    /**
     * Gets the value of the informazioniSupplementariAa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformazioniSupplementariAa() {
        return informazioniSupplementariAa;
    }

    /**
     * Sets the value of the informazioniSupplementariAa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformazioniSupplementariAa(String value) {
        this.informazioniSupplementariAa = value;
    }

    /**
     * Gets the value of the cancellazioneAa property.
     * 
     * @return
     *     possible object is
     *     {@link CancellazioneAa }
     *     
     */
    public CancellazioneAa getCancellazioneAa() {
        return cancellazioneAa;
    }

    /**
     * Sets the value of the cancellazioneAa property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancellazioneAa }
     *     
     */
    public void setCancellazioneAa(CancellazioneAa value) {
        this.cancellazioneAa = value;
    }

    /**
     * Gets the value of the cCategoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCategoria() {
        return cCategoria;
    }

    /**
     * Sets the value of the cCategoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCategoria(String value) {
        this.cCategoria = value;
    }

    /**
     * Gets the value of the categoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoria() {
        return categoria;
    }

    /**
     * Sets the value of the categoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoria(String value) {
        this.categoria = value;
    }

    /**
     * Gets the value of the dtInizio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtInizio() {
        return dtInizio;
    }

    /**
     * Sets the value of the dtInizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtInizio(String value) {
        this.dtInizio = value;
    }

}
