//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for blocchi-impresa element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="blocchi-impresa">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}dati-identificativi" minOccurs="0"/>
 *           &lt;element ref="{}info-sede" minOccurs="0"/>
 *           &lt;element ref="{}estremi-atto-costituzione" minOccurs="0"/>
 *           &lt;element ref="{}cancellazione-trasferimento" minOccurs="0"/>
 *           &lt;element ref="{}info-attivita" minOccurs="0"/>
 *           &lt;element ref="{}storia-attivita" minOccurs="0"/>
 *           &lt;element ref="{}storia-addetti" minOccurs="0"/>
 *           &lt;element ref="{}albi-ruoli-licenze" minOccurs="0"/>
 *           &lt;element ref="{}persone-sede" minOccurs="0"/>
 *           &lt;element ref="{}localizzazioni" minOccurs="0"/>
 *           &lt;element ref="{}protocolli-aperti" minOccurs="0"/>
 *           &lt;element ref="{}protocolli-completi" minOccurs="0"/>
 *           &lt;element ref="{}elenco-soci" minOccurs="0"/>
 *           &lt;element ref="{}annotazioni-libro-soci" minOccurs="0"/>
 *           &lt;element ref="{}trasferimenti-quote" minOccurs="0"/>
 *           &lt;element ref="{}trasferimento-quote" minOccurs="0"/>
 *           &lt;element ref="{}pratiche-soggetti-controllanti" minOccurs="0"/>
 *           &lt;element ref="{}partecipazioni-societa" minOccurs="0"/>
 *           &lt;element ref="{}mad" minOccurs="0"/>
 *           &lt;element ref="{}trascrizioni" minOccurs="0"/>
 *           &lt;element ref="{}storia-cciaa-provenienza" minOccurs="0"/>
 *           &lt;element ref="{}iscrizione-ri" minOccurs="0"/>
 *           &lt;element ref="{}info-statuto" minOccurs="0"/>
 *           &lt;element ref="{}reti-imprese" minOccurs="0"/>
 *           &lt;element ref="{}amministrazione-controllo" minOccurs="0"/>
 *           &lt;element ref="{}info-patrimoniali-finanziarie" minOccurs="0"/>
 *           &lt;element ref="{}patti-parasociali" minOccurs="0"/>
 *           &lt;element ref="{}procedure-concorsuali" minOccurs="0"/>
 *           &lt;element ref="{}variazioni-forma-giuridica" minOccurs="0"/>
 *           &lt;element ref="{}info-supplementari-storiche" minOccurs="0"/>
 *           &lt;element ref="{}ta-fusioni-scissioni-subentri" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datiIdentificativiOrInfoSedeOrEstremiAttoCostituzione"
})
@XmlRootElement(name = "blocchi-impresa")
public class BlocchiImpresa {

    @XmlElements({
        @XmlElement(name = "mad", required = true, type = Mad.class),
        @XmlElement(name = "storia-cciaa-provenienza", required = true, type = StoriaCciaaProvenienza.class),
        @XmlElement(name = "info-statuto", required = true, type = InfoStatuto.class),
        @XmlElement(name = "persone-sede", required = true, type = PersoneSede.class),
        @XmlElement(name = "storia-addetti", required = true, type = StoriaAddetti.class),
        @XmlElement(name = "trasferimenti-quote", required = true, type = TrasferimentiQuote.class),
        @XmlElement(name = "amministrazione-controllo", required = true, type = AmministrazioneControllo.class),
        @XmlElement(name = "variazioni-forma-giuridica", required = true, type = VariazioniFormaGiuridica.class),
        @XmlElement(name = "estremi-atto-costituzione", required = true, type = EstremiAttoCostituzione.class),
        @XmlElement(name = "info-attivita", required = true, type = InfoAttivita.class),
        @XmlElement(name = "dati-identificativi", required = true, type = DatiIdentificativi.class),
        @XmlElement(name = "reti-imprese", required = true, type = RetiImprese.class),
        @XmlElement(name = "pratiche-soggetti-controllanti", required = true, type = PraticheSoggettiControllanti.class),
        @XmlElement(name = "cancellazione-trasferimento", required = true, type = CancellazioneTrasferimento.class),
        @XmlElement(name = "localizzazioni", required = true, type = Localizzazioni.class),
        @XmlElement(name = "storia-attivita", required = true, type = StoriaAttivita.class),
        @XmlElement(name = "info-sede", required = true, type = InfoSede.class),
        @XmlElement(name = "albi-ruoli-licenze", required = true, type = AlbiRuoliLicenze.class),
        @XmlElement(name = "info-patrimoniali-finanziarie", required = true, type = InfoPatrimonialiFinanziarie.class),
        @XmlElement(name = "annotazioni-libro-soci", required = true, type = AnnotazioniLibroSoci.class),
        @XmlElement(name = "ta-fusioni-scissioni-subentri", required = true, type = TaFusioniScissioniSubentri.class),
        @XmlElement(name = "patti-parasociali", required = true, type = PattiParasociali.class),
        @XmlElement(name = "elenco-soci", required = true, type = ElencoSoci.class),
        @XmlElement(name = "trascrizioni", required = true, type = Trascrizioni.class),
        @XmlElement(name = "iscrizione-ri", required = true, type = IscrizioneRi.class),
        @XmlElement(name = "protocolli-completi", required = true, type = ProtocolliCompleti.class),
        @XmlElement(name = "protocolli-aperti", required = true, type = ProtocolliAperti.class),
        @XmlElement(name = "partecipazioni-societa", required = true, type = PartecipazioniSocieta.class),
        @XmlElement(name = "trasferimento-quote", required = true, type = TrasferimentoQuote.class),
        @XmlElement(name = "info-supplementari-storiche", required = true, type = InfoSupplementariStoriche.class),
        @XmlElement(name = "procedure-concorsuali", required = true, type = ProcedureConcorsuali.class)
    })
    protected List<Object> datiIdentificativiOrInfoSedeOrEstremiAttoCostituzione;

    /**
     * Gets the value of the datiIdentificativiOrInfoSedeOrEstremiAttoCostituzione property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datiIdentificativiOrInfoSedeOrEstremiAttoCostituzione property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatiIdentificativiOrInfoSedeOrEstremiAttoCostituzione().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mad }
     * {@link StoriaCciaaProvenienza }
     * {@link InfoStatuto }
     * {@link PersoneSede }
     * {@link StoriaAddetti }
     * {@link TrasferimentiQuote }
     * {@link AmministrazioneControllo }
     * {@link VariazioniFormaGiuridica }
     * {@link EstremiAttoCostituzione }
     * {@link InfoAttivita }
     * {@link DatiIdentificativi }
     * {@link RetiImprese }
     * {@link PraticheSoggettiControllanti }
     * {@link CancellazioneTrasferimento }
     * {@link Localizzazioni }
     * {@link StoriaAttivita }
     * {@link InfoSede }
     * {@link AlbiRuoliLicenze }
     * {@link InfoPatrimonialiFinanziarie }
     * {@link AnnotazioniLibroSoci }
     * {@link TaFusioniScissioniSubentri }
     * {@link PattiParasociali }
     * {@link ElencoSoci }
     * {@link Trascrizioni }
     * {@link IscrizioneRi }
     * {@link ProtocolliCompleti }
     * {@link ProtocolliAperti }
     * {@link PartecipazioniSocieta }
     * {@link TrasferimentoQuote }
     * {@link InfoSupplementariStoriche }
     * {@link ProcedureConcorsuali }
     * 
     * 
     */
    public List<Object> getDatiIdentificativiOrInfoSedeOrEstremiAttoCostituzione() {
        if (datiIdentificativiOrInfoSedeOrEstremiAttoCostituzione == null) {
            datiIdentificativiOrInfoSedeOrEstremiAttoCostituzione = new ArrayList<Object>();
        }
        return this.datiIdentificativiOrInfoSedeOrEstremiAttoCostituzione;
    }

}
