//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for categoria-opere element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="categoria-opere">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="c-categoria" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-classificazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="categoria" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="classificazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "categoria-opere")
public class CategoriaOpere {

    @XmlAttribute(name = "c-categoria")
    protected String cCategoria;
    @XmlAttribute(name = "c-classificazione")
    protected String cClassificazione;
    @XmlAttribute
    protected String categoria;
    @XmlAttribute
    protected String classificazione;

    /**
     * Gets the value of the cCategoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCategoria() {
        return cCategoria;
    }

    /**
     * Sets the value of the cCategoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCategoria(String value) {
        this.cCategoria = value;
    }

    /**
     * Gets the value of the cClassificazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCClassificazione() {
        return cClassificazione;
    }

    /**
     * Sets the value of the cClassificazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCClassificazione(String value) {
        this.cClassificazione = value;
    }

    /**
     * Gets the value of the categoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoria() {
        return categoria;
    }

    /**
     * Sets the value of the categoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoria(String value) {
        this.categoria = value;
    }

    /**
     * Gets the value of the classificazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificazione() {
        return classificazione;
    }

    /**
     * Sets the value of the classificazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificazione(String value) {
        this.classificazione = value;
    }

}
