//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for classificazione-ateco element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="classificazione-ateco">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="attivita" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-attivita" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-importanza" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="dt-inizio" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="dt-riferimento" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="importanza" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "classificazione-ateco")
public class ClassificazioneAteco {

    @XmlAttribute
    protected String attivita;
    @XmlAttribute(name = "c-attivita")
    protected String cAttivita;
    @XmlAttribute(name = "c-importanza")
    protected String cImportanza;
    @XmlAttribute(name = "dt-inizio")
    protected String dtInizio;
    @XmlAttribute(name = "dt-riferimento")
    protected String dtRiferimento;
    @XmlAttribute
    protected String importanza;

    /**
     * Gets the value of the attivita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttivita() {
        return attivita;
    }

    /**
     * Sets the value of the attivita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttivita(String value) {
        this.attivita = value;
    }

    /**
     * Gets the value of the cAttivita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAttivita() {
        return cAttivita;
    }

    /**
     * Sets the value of the cAttivita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAttivita(String value) {
        this.cAttivita = value;
    }

    /**
     * Gets the value of the cImportanza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCImportanza() {
        return cImportanza;
    }

    /**
     * Sets the value of the cImportanza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCImportanza(String value) {
        this.cImportanza = value;
    }

    /**
     * Gets the value of the dtInizio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtInizio() {
        return dtInizio;
    }

    /**
     * Sets the value of the dtInizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtInizio(String value) {
        this.dtInizio = value;
    }

    /**
     * Gets the value of the dtRiferimento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtRiferimento() {
        return dtRiferimento;
    }

    /**
     * Sets the value of the dtRiferimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtRiferimento(String value) {
        this.dtRiferimento = value;
    }

    /**
     * Gets the value of the importanza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportanza() {
        return importanza;
    }

    /**
     * Sets the value of the importanza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportanza(String value) {
        this.importanza = value;
    }

}
