//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for composizione-quote element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="composizione-quote">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="ammontare-convertito-in-euro" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-tipo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-valuta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="n" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="n-azioni" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="n-quote" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="valore-nominale" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="valore-unitario" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="valore-versato" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="valuta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "composizione-quote")
public class ComposizioneQuote {

    @XmlAttribute(name = "ammontare-convertito-in-euro")
    protected String ammontareConvertitoInEuro;
    @XmlAttribute(name = "c-tipo")
    protected String cTipo;
    @XmlAttribute(name = "c-valuta")
    protected String cValuta;
    @XmlAttribute
    protected String n;
    @XmlAttribute(name = "n-azioni")
    protected String nAzioni;
    @XmlAttribute(name = "n-quote")
    protected String nQuote;
    @XmlAttribute
    protected String tipo;
    @XmlAttribute(name = "valore-nominale")
    protected String valoreNominale;
    @XmlAttribute(name = "valore-unitario")
    protected String valoreUnitario;
    @XmlAttribute(name = "valore-versato")
    protected String valoreVersato;
    @XmlAttribute
    protected String valuta;

    /**
     * Gets the value of the ammontareConvertitoInEuro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmmontareConvertitoInEuro() {
        return ammontareConvertitoInEuro;
    }

    /**
     * Sets the value of the ammontareConvertitoInEuro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmmontareConvertitoInEuro(String value) {
        this.ammontareConvertitoInEuro = value;
    }

    /**
     * Gets the value of the cTipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTipo() {
        return cTipo;
    }

    /**
     * Sets the value of the cTipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTipo(String value) {
        this.cTipo = value;
    }

    /**
     * Gets the value of the cValuta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCValuta() {
        return cValuta;
    }

    /**
     * Sets the value of the cValuta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCValuta(String value) {
        this.cValuta = value;
    }

    /**
     * Gets the value of the n property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN() {
        return n;
    }

    /**
     * Sets the value of the n property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN(String value) {
        this.n = value;
    }

    /**
     * Gets the value of the nAzioni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAzioni() {
        return nAzioni;
    }

    /**
     * Sets the value of the nAzioni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAzioni(String value) {
        this.nAzioni = value;
    }

    /**
     * Gets the value of the nQuote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNQuote() {
        return nQuote;
    }

    /**
     * Sets the value of the nQuote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNQuote(String value) {
        this.nQuote = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the valoreNominale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValoreNominale() {
        return valoreNominale;
    }

    /**
     * Sets the value of the valoreNominale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValoreNominale(String value) {
        this.valoreNominale = value;
    }

    /**
     * Gets the value of the valoreUnitario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValoreUnitario() {
        return valoreUnitario;
    }

    /**
     * Sets the value of the valoreUnitario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValoreUnitario(String value) {
        this.valoreUnitario = value;
    }

    /**
     * Gets the value of the valoreVersato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValoreVersato() {
        return valoreVersato;
    }

    /**
     * Sets the value of the valoreVersato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValoreVersato(String value) {
        this.valoreVersato = value;
    }

    /**
     * Gets the value of the valuta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuta() {
        return valuta;
    }

    /**
     * Sets the value of the valuta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuta(String value) {
        this.valuta = value;
    }

}
