//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for indirizzo element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="indirizzo">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="altre-indicazioni" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-comune" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-stato" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-toponimo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="cap" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="comune" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="frazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="n-civico" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="provincia" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="stato" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="toponimo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="via" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "indirizzo")
public class Indirizzo {

    @XmlAttribute(name = "altre-indicazioni")
    protected String altreIndicazioni;
    @XmlAttribute(name = "c-comune")
    protected String cComune;
    @XmlAttribute(name = "c-stato")
    protected String cStato;
    @XmlAttribute(name = "c-toponimo")
    protected String cToponimo;
    @XmlAttribute
    protected String cap;
    @XmlAttribute
    protected String comune;
    @XmlAttribute
    protected String frazione;
    @XmlAttribute(name = "n-civico")
    protected String nCivico;
    @XmlAttribute
    protected String provincia;
    @XmlAttribute
    protected String stato;
    @XmlAttribute
    protected String toponimo;
    @XmlAttribute
    protected String via;

    /**
     * Gets the value of the altreIndicazioni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltreIndicazioni() {
        return altreIndicazioni;
    }

    /**
     * Sets the value of the altreIndicazioni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltreIndicazioni(String value) {
        this.altreIndicazioni = value;
    }

    /**
     * Gets the value of the cComune property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCComune() {
        return cComune;
    }

    /**
     * Sets the value of the cComune property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCComune(String value) {
        this.cComune = value;
    }

    /**
     * Gets the value of the cStato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCStato() {
        return cStato;
    }

    /**
     * Sets the value of the cStato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCStato(String value) {
        this.cStato = value;
    }

    /**
     * Gets the value of the cToponimo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCToponimo() {
        return cToponimo;
    }

    /**
     * Sets the value of the cToponimo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCToponimo(String value) {
        this.cToponimo = value;
    }

    /**
     * Gets the value of the cap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCap() {
        return cap;
    }

    /**
     * Sets the value of the cap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCap(String value) {
        this.cap = value;
    }

    /**
     * Gets the value of the comune property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComune() {
        return comune;
    }

    /**
     * Sets the value of the comune property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComune(String value) {
        this.comune = value;
    }

    /**
     * Gets the value of the frazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrazione() {
        return frazione;
    }

    /**
     * Sets the value of the frazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrazione(String value) {
        this.frazione = value;
    }

    /**
     * Gets the value of the nCivico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNCivico() {
        return nCivico;
    }

    /**
     * Sets the value of the nCivico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNCivico(String value) {
        this.nCivico = value;
    }

    /**
     * Gets the value of the provincia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvincia() {
        return provincia;
    }

    /**
     * Sets the value of the provincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvincia(String value) {
        this.provincia = value;
    }

    /**
     * Gets the value of the stato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStato() {
        return stato;
    }

    /**
     * Sets the value of the stato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStato(String value) {
        this.stato = value;
    }

    /**
     * Gets the value of the toponimo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToponimo() {
        return toponimo;
    }

    /**
     * Sets the value of the toponimo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToponimo(String value) {
        this.toponimo = value;
    }

    /**
     * Gets the value of the via property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVia() {
        return via;
    }

    /**
     * Sets the value of the via property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVia(String value) {
        this.via = value;
    }

}
