//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for iscrizione element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="iscrizione">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="c-categoria" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-tipo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="categoria" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="cciaa" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="dt-assegnazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="dt-iscrizione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="n-marchio" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "iscrizione")
public class Iscrizione {

    @XmlAttribute(name = "c-categoria")
    protected String cCategoria;
    @XmlAttribute(name = "c-tipo")
    protected String cTipo;
    @XmlAttribute
    protected String categoria;
    @XmlAttribute
    protected String cciaa;
    @XmlAttribute(name = "dt-assegnazione")
    protected String dtAssegnazione;
    @XmlAttribute(name = "dt-iscrizione")
    protected String dtIscrizione;
    @XmlAttribute(name = "n-marchio")
    protected String nMarchio;
    @XmlAttribute
    protected String tipo;

    /**
     * Gets the value of the cCategoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCategoria() {
        return cCategoria;
    }

    /**
     * Sets the value of the cCategoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCategoria(String value) {
        this.cCategoria = value;
    }

    /**
     * Gets the value of the cTipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTipo() {
        return cTipo;
    }

    /**
     * Sets the value of the cTipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTipo(String value) {
        this.cTipo = value;
    }

    /**
     * Gets the value of the categoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoria() {
        return categoria;
    }

    /**
     * Sets the value of the categoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoria(String value) {
        this.categoria = value;
    }

    /**
     * Gets the value of the cciaa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCciaa() {
        return cciaa;
    }

    /**
     * Sets the value of the cciaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCciaa(String value) {
        this.cciaa = value;
    }

    /**
     * Gets the value of the dtAssegnazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtAssegnazione() {
        return dtAssegnazione;
    }

    /**
     * Sets the value of the dtAssegnazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtAssegnazione(String value) {
        this.dtAssegnazione = value;
    }

    /**
     * Gets the value of the dtIscrizione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtIscrizione() {
        return dtIscrizione;
    }

    /**
     * Sets the value of the dtIscrizione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtIscrizione(String value) {
        this.dtIscrizione = value;
    }

    /**
     * Gets the value of the nMarchio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNMarchio() {
        return nMarchio;
    }

    /**
     * Sets the value of the nMarchio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNMarchio(String value) {
        this.nMarchio = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

}
