//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for mestiere-aa element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="mestiere-aa">
 *   &lt;complexType>
 *     &lt;simpleContent>
 *       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *         &lt;attribute name="c" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="descrizione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="dt-inizio-attivita" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="ulteriore-descrizione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/extension>
 *     &lt;/simpleContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "mestiere-aa")
public class MestiereAa {

    @XmlValue
    protected String value;
    @XmlAttribute
    protected String c;
    @XmlAttribute
    protected String descrizione;
    @XmlAttribute(name = "dt-inizio-attivita")
    protected String dtInizioAttivita;
    @XmlAttribute(name = "ulteriore-descrizione")
    protected String ulterioreDescrizione;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the c property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getC() {
        return c;
    }

    /**
     * Sets the value of the c property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setC(String value) {
        this.c = value;
    }

    /**
     * Gets the value of the descrizione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * Sets the value of the descrizione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescrizione(String value) {
        this.descrizione = value;
    }

    /**
     * Gets the value of the dtInizioAttivita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtInizioAttivita() {
        return dtInizioAttivita;
    }

    /**
     * Sets the value of the dtInizioAttivita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtInizioAttivita(String value) {
        this.dtInizioAttivita = value;
    }

    /**
     * Gets the value of the ulterioreDescrizione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUlterioreDescrizione() {
        return ulterioreDescrizione;
    }

    /**
     * Sets the value of the ulterioreDescrizione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUlterioreDescrizione(String value) {
        this.ulterioreDescrizione = value;
    }

}
