//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for n-soci element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="n-soci">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="accomandatari" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="amministratori" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="soci" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "n-soci")
public class NSoci {

    @XmlAttribute
    protected String accomandatari;
    @XmlAttribute
    protected String amministratori;
    @XmlAttribute
    protected String soci;

    /**
     * Gets the value of the accomandatari property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccomandatari() {
        return accomandatari;
    }

    /**
     * Sets the value of the accomandatari property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccomandatari(String value) {
        this.accomandatari = value;
    }

    /**
     * Gets the value of the amministratori property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmministratori() {
        return amministratori;
    }

    /**
     * Sets the value of the amministratori property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmministratori(String value) {
        this.amministratori = value;
    }

    /**
     * Gets the value of the soci property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoci() {
        return soci;
    }

    /**
     * Sets the value of the soci property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoci(String value) {
        this.soci = value;
    }

}
