//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for panificatori element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="panificatori">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}caratteristiche-impianto-1" minOccurs="0"/>
 *           &lt;element ref="{}caratteristiche-impianto-2" minOccurs="0"/>
 *           &lt;element ref="{}apparecchi" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "caratteristicheImpianto1",
    "caratteristicheImpianto2",
    "apparecchi"
})
@XmlRootElement(name = "panificatori")
public class Panificatori {

    @XmlElement(name = "caratteristiche-impianto-1")
    protected CaratteristicheImpianto1 caratteristicheImpianto1;
    @XmlElement(name = "caratteristiche-impianto-2")
    protected CaratteristicheImpianto2 caratteristicheImpianto2;
    protected Apparecchi apparecchi;

    /**
     * Gets the value of the caratteristicheImpianto1 property.
     * 
     * @return
     *     possible object is
     *     {@link CaratteristicheImpianto1 }
     *     
     */
    public CaratteristicheImpianto1 getCaratteristicheImpianto1() {
        return caratteristicheImpianto1;
    }

    /**
     * Sets the value of the caratteristicheImpianto1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaratteristicheImpianto1 }
     *     
     */
    public void setCaratteristicheImpianto1(CaratteristicheImpianto1 value) {
        this.caratteristicheImpianto1 = value;
    }

    /**
     * Gets the value of the caratteristicheImpianto2 property.
     * 
     * @return
     *     possible object is
     *     {@link CaratteristicheImpianto2 }
     *     
     */
    public CaratteristicheImpianto2 getCaratteristicheImpianto2() {
        return caratteristicheImpianto2;
    }

    /**
     * Sets the value of the caratteristicheImpianto2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaratteristicheImpianto2 }
     *     
     */
    public void setCaratteristicheImpianto2(CaratteristicheImpianto2 value) {
        this.caratteristicheImpianto2 = value;
    }

    /**
     * Gets the value of the apparecchi property.
     * 
     * @return
     *     possible object is
     *     {@link Apparecchi }
     *     
     */
    public Apparecchi getApparecchi() {
        return apparecchi;
    }

    /**
     * Sets the value of the apparecchi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Apparecchi }
     *     
     */
    public void setApparecchi(Apparecchi value) {
        this.apparecchi = value;
    }

}
