//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parametri element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="parametri">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="dt-estrazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="frase-documento" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="id-richiesta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="sigla-cciaa" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="testata-cciaa" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="titolo-documento" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "parametri")
public class Parametri {

    @XmlAttribute(name = "dt-estrazione")
    protected String dtEstrazione;
    @XmlAttribute(name = "frase-documento")
    protected String fraseDocumento;
    @XmlAttribute(name = "id-richiesta")
    protected String idRichiesta;
    @XmlAttribute(name = "sigla-cciaa")
    protected String siglaCciaa;
    @XmlAttribute(name = "testata-cciaa")
    protected String testataCciaa;
    @XmlAttribute(name = "titolo-documento")
    protected String titoloDocumento;

    /**
     * Gets the value of the dtEstrazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtEstrazione() {
        return dtEstrazione;
    }

    /**
     * Sets the value of the dtEstrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtEstrazione(String value) {
        this.dtEstrazione = value;
    }

    /**
     * Gets the value of the fraseDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraseDocumento() {
        return fraseDocumento;
    }

    /**
     * Sets the value of the fraseDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraseDocumento(String value) {
        this.fraseDocumento = value;
    }

    /**
     * Gets the value of the idRichiesta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdRichiesta() {
        return idRichiesta;
    }

    /**
     * Sets the value of the idRichiesta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdRichiesta(String value) {
        this.idRichiesta = value;
    }

    /**
     * Gets the value of the siglaCciaa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiglaCciaa() {
        return siglaCciaa;
    }

    /**
     * Sets the value of the siglaCciaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiglaCciaa(String value) {
        this.siglaCciaa = value;
    }

    /**
     * Gets the value of the testataCciaa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestataCciaa() {
        return testataCciaa;
    }

    /**
     * Sets the value of the testataCciaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestataCciaa(String value) {
        this.testataCciaa = value;
    }

    /**
     * Gets the value of the titoloDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitoloDocumento() {
        return titoloDocumento;
    }

    /**
     * Sets the value of the titoloDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitoloDocumento(String value) {
        this.titoloDocumento = value;
    }

}
