//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for patti-parasociali element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="patti-parasociali">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}esercizio-diritto-voto" minOccurs="0"/>
 *           &lt;element ref="{}trasferimento-azioni-partecip" minOccurs="0"/>
 *           &lt;element ref="{}esercizio-influenza-dominante" minOccurs="0"/>
 *           &lt;element ref="{}altro" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "esercizioDirittoVoto",
    "trasferimentoAzioniPartecip",
    "esercizioInfluenzaDominante",
    "altro"
})
@XmlRootElement(name = "patti-parasociali")
public class PattiParasociali {

    @XmlElement(name = "esercizio-diritto-voto")
    protected String esercizioDirittoVoto;
    @XmlElement(name = "trasferimento-azioni-partecip")
    protected String trasferimentoAzioniPartecip;
    @XmlElement(name = "esercizio-influenza-dominante")
    protected String esercizioInfluenzaDominante;
    protected String altro;

    /**
     * Gets the value of the esercizioDirittoVoto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEsercizioDirittoVoto() {
        return esercizioDirittoVoto;
    }

    /**
     * Sets the value of the esercizioDirittoVoto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEsercizioDirittoVoto(String value) {
        this.esercizioDirittoVoto = value;
    }

    /**
     * Gets the value of the trasferimentoAzioniPartecip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrasferimentoAzioniPartecip() {
        return trasferimentoAzioniPartecip;
    }

    /**
     * Sets the value of the trasferimentoAzioniPartecip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrasferimentoAzioniPartecip(String value) {
        this.trasferimentoAzioniPartecip = value;
    }

    /**
     * Gets the value of the esercizioInfluenzaDominante property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEsercizioInfluenzaDominante() {
        return esercizioInfluenzaDominante;
    }

    /**
     * Sets the value of the esercizioInfluenzaDominante property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEsercizioInfluenzaDominante(String value) {
        this.esercizioInfluenzaDominante = value;
    }

    /**
     * Gets the value of the altro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltro() {
        return altro;
    }

    /**
     * Sets the value of the altro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltro(String value) {
        this.altro = value;
    }

}
