//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for persona-fisica element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="persona-fisica">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}estremi-nascita" minOccurs="0"/>
 *           &lt;element ref="{}domicilio-fiscale" minOccurs="0"/>
 *           &lt;element ref="{}titoli-onorifici" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="c-capacita-di-agire" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-cittadinanza" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-fiscale" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-precedente-occupazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="c-titolo-studio" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="capacita-di-agire" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="cittadinanza" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="cognome" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="nome" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="precedente-occupazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="sesso" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="titolo-studio" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "estremiNascita",
    "domicilioFiscale",
    "titoliOnorifici"
})
@XmlRootElement(name = "persona-fisica")
public class PersonaFisica {

    @XmlElement(name = "estremi-nascita")
    protected EstremiNascita estremiNascita;
    @XmlElement(name = "domicilio-fiscale")
    protected DomicilioFiscale domicilioFiscale;
    @XmlElement(name = "titoli-onorifici")
    protected TitoliOnorifici titoliOnorifici;
    @XmlAttribute(name = "c-capacita-di-agire")
    protected String cCapacitaDiAgire;
    @XmlAttribute(name = "c-cittadinanza")
    protected String cCittadinanza;
    @XmlAttribute(name = "c-fiscale")
    protected String cFiscale;
    @XmlAttribute(name = "c-precedente-occupazione")
    protected String cPrecedenteOccupazione;
    @XmlAttribute(name = "c-titolo-studio")
    protected String cTitoloStudio;
    @XmlAttribute(name = "capacita-di-agire")
    protected String capacitaDiAgire;
    @XmlAttribute
    protected String cittadinanza;
    @XmlAttribute
    protected String cognome;
    @XmlAttribute
    protected String nome;
    @XmlAttribute(name = "precedente-occupazione")
    protected String precedenteOccupazione;
    @XmlAttribute
    protected String sesso;
    @XmlAttribute(name = "titolo-studio")
    protected String titoloStudio;

    /**
     * Gets the value of the estremiNascita property.
     * 
     * @return
     *     possible object is
     *     {@link EstremiNascita }
     *     
     */
    public EstremiNascita getEstremiNascita() {
        return estremiNascita;
    }

    /**
     * Sets the value of the estremiNascita property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstremiNascita }
     *     
     */
    public void setEstremiNascita(EstremiNascita value) {
        this.estremiNascita = value;
    }

    /**
     * Gets the value of the domicilioFiscale property.
     * 
     * @return
     *     possible object is
     *     {@link DomicilioFiscale }
     *     
     */
    public DomicilioFiscale getDomicilioFiscale() {
        return domicilioFiscale;
    }

    /**
     * Sets the value of the domicilioFiscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomicilioFiscale }
     *     
     */
    public void setDomicilioFiscale(DomicilioFiscale value) {
        this.domicilioFiscale = value;
    }

    /**
     * Gets the value of the titoliOnorifici property.
     * 
     * @return
     *     possible object is
     *     {@link TitoliOnorifici }
     *     
     */
    public TitoliOnorifici getTitoliOnorifici() {
        return titoliOnorifici;
    }

    /**
     * Sets the value of the titoliOnorifici property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitoliOnorifici }
     *     
     */
    public void setTitoliOnorifici(TitoliOnorifici value) {
        this.titoliOnorifici = value;
    }

    /**
     * Gets the value of the cCapacitaDiAgire property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCapacitaDiAgire() {
        return cCapacitaDiAgire;
    }

    /**
     * Sets the value of the cCapacitaDiAgire property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCapacitaDiAgire(String value) {
        this.cCapacitaDiAgire = value;
    }

    /**
     * Gets the value of the cCittadinanza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCittadinanza() {
        return cCittadinanza;
    }

    /**
     * Sets the value of the cCittadinanza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCittadinanza(String value) {
        this.cCittadinanza = value;
    }

    /**
     * Gets the value of the cFiscale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCFiscale() {
        return cFiscale;
    }

    /**
     * Sets the value of the cFiscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCFiscale(String value) {
        this.cFiscale = value;
    }

    /**
     * Gets the value of the cPrecedenteOccupazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPrecedenteOccupazione() {
        return cPrecedenteOccupazione;
    }

    /**
     * Sets the value of the cPrecedenteOccupazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPrecedenteOccupazione(String value) {
        this.cPrecedenteOccupazione = value;
    }

    /**
     * Gets the value of the cTitoloStudio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTitoloStudio() {
        return cTitoloStudio;
    }

    /**
     * Sets the value of the cTitoloStudio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTitoloStudio(String value) {
        this.cTitoloStudio = value;
    }

    /**
     * Gets the value of the capacitaDiAgire property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapacitaDiAgire() {
        return capacitaDiAgire;
    }

    /**
     * Sets the value of the capacitaDiAgire property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapacitaDiAgire(String value) {
        this.capacitaDiAgire = value;
    }

    /**
     * Gets the value of the cittadinanza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCittadinanza() {
        return cittadinanza;
    }

    /**
     * Sets the value of the cittadinanza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCittadinanza(String value) {
        this.cittadinanza = value;
    }

    /**
     * Gets the value of the cognome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCognome() {
        return cognome;
    }

    /**
     * Sets the value of the cognome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCognome(String value) {
        this.cognome = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the precedenteOccupazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecedenteOccupazione() {
        return precedenteOccupazione;
    }

    /**
     * Sets the value of the precedenteOccupazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecedenteOccupazione(String value) {
        this.precedenteOccupazione = value;
    }

    /**
     * Gets the value of the sesso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSesso() {
        return sesso;
    }

    /**
     * Sets the value of the sesso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSesso(String value) {
        this.sesso = value;
    }

    /**
     * Gets the value of the titoloStudio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitoloStudio() {
        return titoloStudio;
    }

    /**
     * Sets the value of the titoloStudio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitoloStudio(String value) {
        this.titoloStudio = value;
    }

}
