//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for procedure-concorsuali element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="procedure-concorsuali">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}procedura-concorsuale" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}comunicazioni-curatore" minOccurs="0"/>
 *           &lt;element ref="{}informazioni-curatore" minOccurs="0"/>
 *           &lt;element ref="{}accordi-debiti" minOccurs="0"/>
 *           &lt;element ref="{}rapporto-curatore" minOccurs="0"/>
 *           &lt;element ref="{}appelli-reclami" minOccurs="0"/>
 *           &lt;element ref="{}proposta-concordato" minOccurs="0"/>
 *           &lt;element ref="{}esercizio-provvisorio" minOccurs="0"/>
 *           &lt;element ref="{}continuazione-esercizio-provv" minOccurs="0"/>
 *           &lt;element ref="{}cessazione-esercizio-provv" minOccurs="0"/>
 *           &lt;element ref="{}esecuzione-concordato" minOccurs="0"/>
 *           &lt;element ref="{}annotazioni-procedure" minOccurs="0"/>
 *           &lt;element ref="{}persone-pco" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="cciaa-fuori-provincia" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="f-presenza-info" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "proceduraConcorsuale",
    "comunicazioniCuratore",
    "informazioniCuratore",
    "accordiDebiti",
    "rapportoCuratore",
    "appelliReclami",
    "propostaConcordato",
    "esercizioProvvisorio",
    "continuazioneEsercizioProvv",
    "cessazioneEsercizioProvv",
    "esecuzioneConcordato",
    "annotazioniProcedure",
    "personePco"
})
@XmlRootElement(name = "procedure-concorsuali")
public class ProcedureConcorsuali {

    @XmlElement(name = "procedura-concorsuale", required = true)
    protected List<ProceduraConcorsuale> proceduraConcorsuale;
    @XmlElement(name = "comunicazioni-curatore")
    protected ComunicazioniCuratore comunicazioniCuratore;
    @XmlElement(name = "informazioni-curatore")
    protected String informazioniCuratore;
    @XmlElement(name = "accordi-debiti")
    protected String accordiDebiti;
    @XmlElement(name = "rapporto-curatore")
    protected String rapportoCuratore;
    @XmlElement(name = "appelli-reclami")
    protected String appelliReclami;
    @XmlElement(name = "proposta-concordato")
    protected String propostaConcordato;
    @XmlElement(name = "esercizio-provvisorio")
    protected String esercizioProvvisorio;
    @XmlElement(name = "continuazione-esercizio-provv")
    protected String continuazioneEsercizioProvv;
    @XmlElement(name = "cessazione-esercizio-provv")
    protected String cessazioneEsercizioProvv;
    @XmlElement(name = "esecuzione-concordato")
    protected String esecuzioneConcordato;
    @XmlElement(name = "annotazioni-procedure")
    protected String annotazioniProcedure;
    @XmlElement(name = "persone-pco")
    protected PersonePco personePco;
    @XmlAttribute(name = "cciaa-fuori-provincia")
    protected String cciaaFuoriProvincia;
    @XmlAttribute(name = "f-presenza-info")
    protected String fPresenzaInfo;

    /**
     * Gets the value of the proceduraConcorsuale property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the proceduraConcorsuale property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProceduraConcorsuale().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProceduraConcorsuale }
     * 
     * 
     */
    public List<ProceduraConcorsuale> getProceduraConcorsuale() {
        if (proceduraConcorsuale == null) {
            proceduraConcorsuale = new ArrayList<ProceduraConcorsuale>();
        }
        return this.proceduraConcorsuale;
    }

    /**
     * Gets the value of the comunicazioniCuratore property.
     * 
     * @return
     *     possible object is
     *     {@link ComunicazioniCuratore }
     *     
     */
    public ComunicazioniCuratore getComunicazioniCuratore() {
        return comunicazioniCuratore;
    }

    /**
     * Sets the value of the comunicazioniCuratore property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComunicazioniCuratore }
     *     
     */
    public void setComunicazioniCuratore(ComunicazioniCuratore value) {
        this.comunicazioniCuratore = value;
    }

    /**
     * Gets the value of the informazioniCuratore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformazioniCuratore() {
        return informazioniCuratore;
    }

    /**
     * Sets the value of the informazioniCuratore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformazioniCuratore(String value) {
        this.informazioniCuratore = value;
    }

    /**
     * Gets the value of the accordiDebiti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccordiDebiti() {
        return accordiDebiti;
    }

    /**
     * Sets the value of the accordiDebiti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccordiDebiti(String value) {
        this.accordiDebiti = value;
    }

    /**
     * Gets the value of the rapportoCuratore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRapportoCuratore() {
        return rapportoCuratore;
    }

    /**
     * Sets the value of the rapportoCuratore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRapportoCuratore(String value) {
        this.rapportoCuratore = value;
    }

    /**
     * Gets the value of the appelliReclami property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppelliReclami() {
        return appelliReclami;
    }

    /**
     * Sets the value of the appelliReclami property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppelliReclami(String value) {
        this.appelliReclami = value;
    }

    /**
     * Gets the value of the propostaConcordato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropostaConcordato() {
        return propostaConcordato;
    }

    /**
     * Sets the value of the propostaConcordato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropostaConcordato(String value) {
        this.propostaConcordato = value;
    }

    /**
     * Gets the value of the esercizioProvvisorio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEsercizioProvvisorio() {
        return esercizioProvvisorio;
    }

    /**
     * Sets the value of the esercizioProvvisorio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEsercizioProvvisorio(String value) {
        this.esercizioProvvisorio = value;
    }

    /**
     * Gets the value of the continuazioneEsercizioProvv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContinuazioneEsercizioProvv() {
        return continuazioneEsercizioProvv;
    }

    /**
     * Sets the value of the continuazioneEsercizioProvv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContinuazioneEsercizioProvv(String value) {
        this.continuazioneEsercizioProvv = value;
    }

    /**
     * Gets the value of the cessazioneEsercizioProvv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCessazioneEsercizioProvv() {
        return cessazioneEsercizioProvv;
    }

    /**
     * Sets the value of the cessazioneEsercizioProvv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCessazioneEsercizioProvv(String value) {
        this.cessazioneEsercizioProvv = value;
    }

    /**
     * Gets the value of the esecuzioneConcordato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEsecuzioneConcordato() {
        return esecuzioneConcordato;
    }

    /**
     * Sets the value of the esecuzioneConcordato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEsecuzioneConcordato(String value) {
        this.esecuzioneConcordato = value;
    }

    /**
     * Gets the value of the annotazioniProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotazioniProcedure() {
        return annotazioniProcedure;
    }

    /**
     * Sets the value of the annotazioniProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotazioniProcedure(String value) {
        this.annotazioniProcedure = value;
    }

    /**
     * Gets the value of the personePco property.
     * 
     * @return
     *     possible object is
     *     {@link PersonePco }
     *     
     */
    public PersonePco getPersonePco() {
        return personePco;
    }

    /**
     * Sets the value of the personePco property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonePco }
     *     
     */
    public void setPersonePco(PersonePco value) {
        this.personePco = value;
    }

    /**
     * Gets the value of the cciaaFuoriProvincia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCciaaFuoriProvincia() {
        return cciaaFuoriProvincia;
    }

    /**
     * Sets the value of the cciaaFuoriProvincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCciaaFuoriProvincia(String value) {
        this.cciaaFuoriProvincia = value;
    }

    /**
     * Gets the value of the fPresenzaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPresenzaInfo() {
        return fPresenzaInfo;
    }

    /**
     * Sets the value of the fPresenzaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPresenzaInfo(String value) {
        this.fPresenzaInfo = value;
    }

}
