//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for protocolli-aperti element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="protocolli-aperti">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}protocollo-aperto" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="f-presenza-info" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "protocolloAperto"
})
@XmlRootElement(name = "protocolli-aperti")
public class ProtocolliAperti {

    @XmlElement(name = "protocollo-aperto", required = true)
    protected List<ProtocolloAperto> protocolloAperto;
    @XmlAttribute(name = "f-presenza-info")
    protected String fPresenzaInfo;

    /**
     * Gets the value of the protocolloAperto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the protocolloAperto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProtocolloAperto().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProtocolloAperto }
     * 
     * 
     */
    public List<ProtocolloAperto> getProtocolloAperto() {
        if (protocolloAperto == null) {
            protocolloAperto = new ArrayList<ProtocolloAperto>();
        }
        return this.protocolloAperto;
    }

    /**
     * Gets the value of the fPresenzaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPresenzaInfo() {
        return fPresenzaInfo;
    }

    /**
     * Sets the value of the fPresenzaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPresenzaInfo(String value) {
        this.fPresenzaInfo = value;
    }

}
