//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for protocolli-completi element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="protocolli-completi">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}protocolli" minOccurs="0"/>
 *           &lt;element ref="{}trascrizioni-prot-completi" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="dt-domenica-precedente" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="dt-estrazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="dt-lunedi-precedente" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="f-presenza-info" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "protocolli",
    "trascrizioniProtCompleti"
})
@XmlRootElement(name = "protocolli-completi")
public class ProtocolliCompleti {

    protected Protocolli protocolli;
    @XmlElement(name = "trascrizioni-prot-completi")
    protected TrascrizioniProtCompleti trascrizioniProtCompleti;
    @XmlAttribute(name = "dt-domenica-precedente")
    protected String dtDomenicaPrecedente;
    @XmlAttribute(name = "dt-estrazione")
    protected String dtEstrazione;
    @XmlAttribute(name = "dt-lunedi-precedente")
    protected String dtLunediPrecedente;
    @XmlAttribute(name = "f-presenza-info")
    protected String fPresenzaInfo;

    /**
     * Gets the value of the protocolli property.
     * 
     * @return
     *     possible object is
     *     {@link Protocolli }
     *     
     */
    public Protocolli getProtocolli() {
        return protocolli;
    }

    /**
     * Sets the value of the protocolli property.
     * 
     * @param value
     *     allowed object is
     *     {@link Protocolli }
     *     
     */
    public void setProtocolli(Protocolli value) {
        this.protocolli = value;
    }

    /**
     * Gets the value of the trascrizioniProtCompleti property.
     * 
     * @return
     *     possible object is
     *     {@link TrascrizioniProtCompleti }
     *     
     */
    public TrascrizioniProtCompleti getTrascrizioniProtCompleti() {
        return trascrizioniProtCompleti;
    }

    /**
     * Sets the value of the trascrizioniProtCompleti property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrascrizioniProtCompleti }
     *     
     */
    public void setTrascrizioniProtCompleti(TrascrizioniProtCompleti value) {
        this.trascrizioniProtCompleti = value;
    }

    /**
     * Gets the value of the dtDomenicaPrecedente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtDomenicaPrecedente() {
        return dtDomenicaPrecedente;
    }

    /**
     * Sets the value of the dtDomenicaPrecedente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtDomenicaPrecedente(String value) {
        this.dtDomenicaPrecedente = value;
    }

    /**
     * Gets the value of the dtEstrazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtEstrazione() {
        return dtEstrazione;
    }

    /**
     * Sets the value of the dtEstrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtEstrazione(String value) {
        this.dtEstrazione = value;
    }

    /**
     * Gets the value of the dtLunediPrecedente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtLunediPrecedente() {
        return dtLunediPrecedente;
    }

    /**
     * Sets the value of the dtLunediPrecedente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtLunediPrecedente(String value) {
        this.dtLunediPrecedente = value;
    }

    /**
     * Gets the value of the fPresenzaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPresenzaInfo() {
        return fPresenzaInfo;
    }

    /**
     * Sets the value of the fPresenzaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPresenzaInfo(String value) {
        this.fPresenzaInfo = value;
    }

}
