//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sessione-rd-rea element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="sessione-rd-rea">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}modifiche"/>
 *         &lt;/sequence>
 *         &lt;attribute name="c-movimentazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="dt-denuncia" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="movimentazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modifiche"
})
@XmlRootElement(name = "sessione-rd-rea")
public class SessioneRdRea {

    @XmlElement(required = true)
    protected Modifiche modifiche;
    @XmlAttribute(name = "c-movimentazione")
    protected String cMovimentazione;
    @XmlAttribute(name = "dt-denuncia")
    protected String dtDenuncia;
    @XmlAttribute
    protected String movimentazione;

    /**
     * Gets the value of the modifiche property.
     * 
     * @return
     *     possible object is
     *     {@link Modifiche }
     *     
     */
    public Modifiche getModifiche() {
        return modifiche;
    }

    /**
     * Sets the value of the modifiche property.
     * 
     * @param value
     *     allowed object is
     *     {@link Modifiche }
     *     
     */
    public void setModifiche(Modifiche value) {
        this.modifiche = value;
    }

    /**
     * Gets the value of the cMovimentazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMovimentazione() {
        return cMovimentazione;
    }

    /**
     * Sets the value of the cMovimentazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMovimentazione(String value) {
        this.cMovimentazione = value;
    }

    /**
     * Gets the value of the dtDenuncia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtDenuncia() {
        return dtDenuncia;
    }

    /**
     * Sets the value of the dtDenuncia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtDenuncia(String value) {
        this.dtDenuncia = value;
    }

    /**
     * Gets the value of the movimentazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMovimentazione() {
        return movimentazione;
    }

    /**
     * Sets the value of the movimentazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMovimentazione(String value) {
        this.movimentazione = value;
    }

}
