//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for subentri-impresa element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="subentri-impresa">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}impresa-subentrata" minOccurs="0"/>
 *           &lt;element ref="{}subentri" minOccurs="0"/>
 *           &lt;element ref="{}impresa-subentrante" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "impresaSubentrata",
    "subentri",
    "impresaSubentrante"
})
@XmlRootElement(name = "subentri-impresa")
public class SubentriImpresa {

    @XmlElement(name = "impresa-subentrata")
    protected ImpresaSubentrata impresaSubentrata;
    protected Subentri subentri;
    @XmlElement(name = "impresa-subentrante")
    protected ImpresaSubentrante impresaSubentrante;

    /**
     * Gets the value of the impresaSubentrata property.
     * 
     * @return
     *     possible object is
     *     {@link ImpresaSubentrata }
     *     
     */
    public ImpresaSubentrata getImpresaSubentrata() {
        return impresaSubentrata;
    }

    /**
     * Sets the value of the impresaSubentrata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImpresaSubentrata }
     *     
     */
    public void setImpresaSubentrata(ImpresaSubentrata value) {
        this.impresaSubentrata = value;
    }

    /**
     * Gets the value of the subentri property.
     * 
     * @return
     *     possible object is
     *     {@link Subentri }
     *     
     */
    public Subentri getSubentri() {
        return subentri;
    }

    /**
     * Sets the value of the subentri property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subentri }
     *     
     */
    public void setSubentri(Subentri value) {
        this.subentri = value;
    }

    /**
     * Gets the value of the impresaSubentrante property.
     * 
     * @return
     *     possible object is
     *     {@link ImpresaSubentrante }
     *     
     */
    public ImpresaSubentrante getImpresaSubentrante() {
        return impresaSubentrante;
    }

    /**
     * Sets the value of the impresaSubentrante property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImpresaSubentrante }
     *     
     */
    public void setImpresaSubentrante(ImpresaSubentrante value) {
        this.impresaSubentrante = value;
    }

}
