//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for tabelle-speciali element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="tabelle-speciali">
 *   &lt;complexType>
 *     &lt;simpleContent>
 *       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *         &lt;attribute name="f-farmacia" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="f-vendita-carburanti" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="f-vendita-generi-monopolio" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="mq" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/extension>
 *     &lt;/simpleContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "tabelle-speciali")
public class TabelleSpeciali {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "f-farmacia")
    protected String fFarmacia;
    @XmlAttribute(name = "f-vendita-carburanti")
    protected String fVenditaCarburanti;
    @XmlAttribute(name = "f-vendita-generi-monopolio")
    protected String fVenditaGeneriMonopolio;
    @XmlAttribute
    protected String mq;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the fFarmacia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFFarmacia() {
        return fFarmacia;
    }

    /**
     * Sets the value of the fFarmacia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFFarmacia(String value) {
        this.fFarmacia = value;
    }

    /**
     * Gets the value of the fVenditaCarburanti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFVenditaCarburanti() {
        return fVenditaCarburanti;
    }

    /**
     * Sets the value of the fVenditaCarburanti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFVenditaCarburanti(String value) {
        this.fVenditaCarburanti = value;
    }

    /**
     * Gets the value of the fVenditaGeneriMonopolio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFVenditaGeneriMonopolio() {
        return fVenditaGeneriMonopolio;
    }

    /**
     * Sets the value of the fVenditaGeneriMonopolio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFVenditaGeneriMonopolio(String value) {
        this.fVenditaGeneriMonopolio = value;
    }

    /**
     * Gets the value of the mq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMq() {
        return mq;
    }

    /**
     * Sets the value of the mq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMq(String value) {
        this.mq = value;
    }

}
