//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:18:12 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tipi-procedure-concorsuali element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="tipi-procedure-concorsuali">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}tipo-procedura-concorsuale" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="cciaa-fuori-provincia" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tipoProceduraConcorsuale"
})
@XmlRootElement(name = "tipi-procedure-concorsuali")
public class TipiProcedureConcorsuali {

    @XmlElement(name = "tipo-procedura-concorsuale", required = true)
    protected List<TipoProceduraConcorsuale> tipoProceduraConcorsuale;
    @XmlAttribute(name = "cciaa-fuori-provincia")
    protected String cciaaFuoriProvincia;

    /**
     * Gets the value of the tipoProceduraConcorsuale property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tipoProceduraConcorsuale property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTipoProceduraConcorsuale().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoProceduraConcorsuale }
     * 
     * 
     */
    public List<TipoProceduraConcorsuale> getTipoProceduraConcorsuale() {
        if (tipoProceduraConcorsuale == null) {
            tipoProceduraConcorsuale = new ArrayList<TipoProceduraConcorsuale>();
        }
        return this.tipoProceduraConcorsuale;
    }

    /**
     * Gets the value of the cciaaFuoriProvincia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCciaaFuoriProvincia() {
        return cciaaFuoriProvincia;
    }

    /**
     * Sets the value of the cciaaFuoriProvincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCciaaFuoriProvincia(String value) {
        this.cciaaFuoriProvincia = value;
    }

}
