//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 08:35:14 PM CEST 
//


package it.vidoc.registro.protesti.visura.effetto.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VisuraEffetto_QNAME = new QName("", "VisuraEffetto");
    private final static QName _Messaggio_QNAME = new QName("", "Messaggio");
    private final static QName _Testata_QNAME = new QName("", "Testata");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestataType }
     * 
     */
    public TestataType createTestataType() {
        return new TestataType();
    }

    /**
     * Create an instance of {@link InfoAggiuntiveEffettoType }
     * 
     */
    public InfoAggiuntiveEffettoType createInfoAggiuntiveEffettoType() {
        return new InfoAggiuntiveEffettoType();
    }

    /**
     * Create an instance of {@link Risposta }
     * 
     */
    public Risposta createRisposta() {
        return new Risposta();
    }

    /**
     * Create an instance of {@link MessaggioType }
     * 
     */
    public MessaggioType createMessaggioType() {
        return new MessaggioType();
    }

    /**
     * Create an instance of {@link InformazioniEffettoType }
     * 
     */
    public InformazioniEffettoType createInformazioniEffettoType() {
        return new InformazioniEffettoType();
    }

    /**
     * Create an instance of {@link AnagraficaType }
     * 
     */
    public AnagraficaType createAnagraficaType() {
        return new AnagraficaType();
    }

    /**
     * Create an instance of {@link DatiRegistroProtestiType }
     * 
     */
    public DatiRegistroProtestiType createDatiRegistroProtestiType() {
        return new DatiRegistroProtestiType();
    }

    /**
     * Create an instance of {@link DatiArchivioStoricoType }
     * 
     */
    public DatiArchivioStoricoType createDatiArchivioStoricoType() {
        return new DatiArchivioStoricoType();
    }

    /**
     * Create an instance of {@link VisuraEffettoType }
     * 
     */
    public VisuraEffettoType createVisuraEffettoType() {
        return new VisuraEffettoType();
    }

    /**
     * Create an instance of {@link RegistroProtestiType }
     * 
     */
    public RegistroProtestiType createRegistroProtestiType() {
        return new RegistroProtestiType();
    }

    /**
     * Create an instance of {@link ArchivioStoricoType }
     * 
     */
    public ArchivioStoricoType createArchivioStoricoType() {
        return new ArchivioStoricoType();
    }

    /**
     * Create an instance of {@link Dati }
     * 
     */
    public Dati createDati() {
        return new Dati();
    }

    /**
     * Create an instance of {@link RiepilogoType }
     * 
     */
    public RiepilogoType createRiepilogoType() {
        return new RiepilogoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VisuraEffettoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VisuraEffetto")
    public JAXBElement<VisuraEffettoType> createVisuraEffetto(VisuraEffettoType value) {
        return new JAXBElement<VisuraEffettoType>(_VisuraEffetto_QNAME, VisuraEffettoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessaggioType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Messaggio")
    public JAXBElement<MessaggioType> createMessaggio(MessaggioType value) {
        return new JAXBElement<MessaggioType>(_Messaggio_QNAME, MessaggioType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Testata")
    public JAXBElement<TestataType> createTestata(TestataType value) {
        return new JAXBElement<TestataType>(_Testata_QNAME, TestataType.class, null, value);
    }

}
