//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 08:33:16 PM CEST 
//


package it.vidoc.registro.protesti.lista.ufficiali.levatori.response;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodUffLevType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodUffLevType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SglPrvRegUffLev" type="{}CciaaType"/>
 *         &lt;element name="DescPrvRegUffLev" type="{}DescrizioneType"/>
 *         &lt;element name="CodTipoUffLev" type="{}CodTipoUffLevType"/>
 *         &lt;element name="DescTipoUffLev" type="{}DescrizioneType"/>
 *         &lt;element name="NUffLev" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodUffLevType", propOrder = {
    "sglPrvRegUffLev",
    "descPrvRegUffLev",
    "codTipoUffLev",
    "descTipoUffLev",
    "nUffLev"
})
public class CodUffLevType {

    @XmlElement(name = "SglPrvRegUffLev", required = true)
    protected String sglPrvRegUffLev;
    @XmlElement(name = "DescPrvRegUffLev", required = true)
    protected String descPrvRegUffLev;
    @XmlElement(name = "CodTipoUffLev", required = true)
    protected String codTipoUffLev;
    @XmlElement(name = "DescTipoUffLev", required = true)
    protected String descTipoUffLev;
    @XmlElement(name = "NUffLev", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger nUffLev;

    /**
     * Gets the value of the sglPrvRegUffLev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSglPrvRegUffLev() {
        return sglPrvRegUffLev;
    }

    /**
     * Sets the value of the sglPrvRegUffLev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSglPrvRegUffLev(String value) {
        this.sglPrvRegUffLev = value;
    }

    /**
     * Gets the value of the descPrvRegUffLev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescPrvRegUffLev() {
        return descPrvRegUffLev;
    }

    /**
     * Sets the value of the descPrvRegUffLev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescPrvRegUffLev(String value) {
        this.descPrvRegUffLev = value;
    }

    /**
     * Gets the value of the codTipoUffLev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodTipoUffLev() {
        return codTipoUffLev;
    }

    /**
     * Sets the value of the codTipoUffLev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodTipoUffLev(String value) {
        this.codTipoUffLev = value;
    }

    /**
     * Gets the value of the descTipoUffLev property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescTipoUffLev() {
        return descTipoUffLev;
    }

    /**
     * Sets the value of the descTipoUffLev property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescTipoUffLev(String value) {
        this.descTipoUffLev = value;
    }

    /**
     * Gets the value of the nUffLev property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNUffLev() {
        return nUffLev;
    }

    /**
     * Sets the value of the nUffLev property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNUffLev(BigInteger value) {
        this.nUffLev = value;
    }

}
