//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:16:18 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InformazioniImpresaPdfType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InformazioniImpresaPdfType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="PerChiaveReaPdf" type="{}PerChiaveReaPdfType"/>
 *         &lt;element name="PerCodFiscSedePdf" type="{}PerCodFiscSedePdfType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InformazioniImpresaPdfType", propOrder = {
    "perChiaveReaPdf",
    "perCodFiscSedePdf"
})
public class InformazioniImpresaPdfType {

    @XmlElement(name = "PerChiaveReaPdf")
    protected PerChiaveReaPdfType perChiaveReaPdf;
    @XmlElement(name = "PerCodFiscSedePdf")
    protected PerCodFiscSedePdfType perCodFiscSedePdf;

    /**
     * Gets the value of the perChiaveReaPdf property.
     * 
     * @return
     *     possible object is
     *     {@link PerChiaveReaPdfType }
     *     
     */
    public PerChiaveReaPdfType getPerChiaveReaPdf() {
        return perChiaveReaPdf;
    }

    /**
     * Sets the value of the perChiaveReaPdf property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerChiaveReaPdfType }
     *     
     */
    public void setPerChiaveReaPdf(PerChiaveReaPdfType value) {
        this.perChiaveReaPdf = value;
    }

    /**
     * Gets the value of the perCodFiscSedePdf property.
     * 
     * @return
     *     possible object is
     *     {@link PerCodFiscSedePdfType }
     *     
     */
    public PerCodFiscSedePdfType getPerCodFiscSedePdf() {
        return perCodFiscSedePdf;
    }

    /**
     * Sets the value of the perCodFiscSedePdf property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerCodFiscSedePdfType }
     *     
     */
    public void setPerCodFiscSedePdf(PerCodFiscSedePdfType value) {
        this.perCodFiscSedePdf = value;
    }

}
