//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:16:18 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.request;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for ListaBlocchiDiffType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ListaBlocchiDiffType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ALB"/>
 *     &lt;enumeration value="AMM"/>
 *     &lt;enumeration value="APE"/>
 *     &lt;enumeration value="CAP"/>
 *     &lt;enumeration value="CON"/>
 *     &lt;enumeration value="COS"/>
 *     &lt;enumeration value="IPA"/>
 *     &lt;enumeration value="PAR"/>
 *     &lt;enumeration value="PAS"/>
 *     &lt;enumeration value="PCO"/>
 *     &lt;enumeration value="PER"/>
 *     &lt;enumeration value="PRA"/>
 *     &lt;enumeration value="QUO"/>
 *     &lt;enumeration value="SIN"/>
 *     &lt;enumeration value="SOC"/>
 *     &lt;enumeration value="SOS"/>
 *     &lt;enumeration value="STO"/>
 *     &lt;enumeration value="SUL"/>
 *     &lt;enumeration value="TFS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ListaBlocchiDiffType {

    ALB,
    AMM,
    APE,
    CAP,
    CON,
    COS,
    IPA,
    PAR,
    PAS,
    PCO,
    PER,
    PRA,
    QUO,
    SIN,
    SOC,
    SOS,
    STO,
    SUL,
    TFS;

    public String value() {
        return name();
    }

    public static ListaBlocchiDiffType fromValue(String v) {
        return valueOf(v);
    }

}
