//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:16:18 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RichiestaPerChiaveBilancioType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RichiestaPerChiaveBilancioType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KRea" type="{}KReaType"/>
 *         &lt;element name="DtChiusuraBil" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="CodAtto" type="{}CodAttoType"/>
 *         &lt;element name="FBilRipresentato" type="{}FBilRipresentatoType" minOccurs="0"/>
 *         &lt;element name="ProgSezione" type="{}ProgSezioneType" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="IdeRich" type="{}IdeRichType" minOccurs="0"/>
 *         &lt;element name="ErogaXbrl" type="{}ErogaXbrlType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RichiestaPerChiaveBilancioType", propOrder = {
    "kRea",
    "dtChiusuraBil",
    "codAtto",
    "fBilRipresentato",
    "progSezione",
    "ideRich",
    "erogaXbrl"
})
public class RichiestaPerChiaveBilancioType {

    @XmlElement(name = "KRea", required = true)
    protected KReaType kRea;
    @XmlElement(name = "DtChiusuraBil", required = true)
    protected XMLGregorianCalendar dtChiusuraBil;
    @XmlElement(name = "CodAtto", required = true)
    protected String codAtto;
    @XmlElement(name = "FBilRipresentato")
    protected String fBilRipresentato;
    @XmlElement(name = "ProgSezione", required = true)
    protected List<String> progSezione;
    @XmlElement(name = "IdeRich")
    protected String ideRich;
    @XmlElement(name = "ErogaXbrl")
    protected ErogaXbrlType erogaXbrl;

    /**
     * Gets the value of the kRea property.
     * 
     * @return
     *     possible object is
     *     {@link KReaType }
     *     
     */
    public KReaType getKRea() {
        return kRea;
    }

    /**
     * Sets the value of the kRea property.
     * 
     * @param value
     *     allowed object is
     *     {@link KReaType }
     *     
     */
    public void setKRea(KReaType value) {
        this.kRea = value;
    }

    /**
     * Gets the value of the dtChiusuraBil property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtChiusuraBil() {
        return dtChiusuraBil;
    }

    /**
     * Sets the value of the dtChiusuraBil property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtChiusuraBil(XMLGregorianCalendar value) {
        this.dtChiusuraBil = value;
    }

    /**
     * Gets the value of the codAtto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodAtto() {
        return codAtto;
    }

    /**
     * Sets the value of the codAtto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodAtto(String value) {
        this.codAtto = value;
    }

    /**
     * Gets the value of the fBilRipresentato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFBilRipresentato() {
        return fBilRipresentato;
    }

    /**
     * Sets the value of the fBilRipresentato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFBilRipresentato(String value) {
        this.fBilRipresentato = value;
    }

    /**
     * Gets the value of the progSezione property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the progSezione property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProgSezione().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProgSezione() {
        if (progSezione == null) {
            progSezione = new ArrayList<String>();
        }
        return this.progSezione;
    }

    /**
     * Gets the value of the ideRich property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdeRich() {
        return ideRich;
    }

    /**
     * Sets the value of the ideRich property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdeRich(String value) {
        this.ideRich = value;
    }

    /**
     * Gets the value of the erogaXbrl property.
     * 
     * @return
     *     possible object is
     *     {@link ErogaXbrlType }
     *     
     */
    public ErogaXbrlType getErogaXbrl() {
        return erogaXbrl;
    }

    /**
     * Sets the value of the erogaXbrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErogaXbrlType }
     *     
     */
    public void setErogaXbrl(ErogaXbrlType value) {
        this.erogaXbrl = value;
    }

}
