//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 06:16:18 PM CEST 
//


package it.vidoc.registro.imprese.output.ri.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatutoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatutoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="RichiestaPerChiaveRea" type="{}RichiestaPerChiaveReaType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatutoType", propOrder = {
    "richiestaPerChiaveRea"
})
public class StatutoType {

    @XmlElement(name = "RichiestaPerChiaveRea")
    protected RichiestaPerChiaveReaType richiestaPerChiaveRea;

    /**
     * Gets the value of the richiestaPerChiaveRea property.
     * 
     * @return
     *     possible object is
     *     {@link RichiestaPerChiaveReaType }
     *     
     */
    public RichiestaPerChiaveReaType getRichiestaPerChiaveRea() {
        return richiestaPerChiaveRea;
    }

    /**
     * Sets the value of the richiestaPerChiaveRea property.
     * 
     * @param value
     *     allowed object is
     *     {@link RichiestaPerChiaveReaType }
     *     
     */
    public void setRichiestaPerChiaveRea(RichiestaPerChiaveReaType value) {
        this.richiestaPerChiaveRea = value;
    }

}
