//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 05:57:20 PM CEST 
//


package it.vidoc.registro.imprese.ricerca.anagrafica.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.vidoc.registro.imprese.request.ricerca.anagrafica package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RicercaAnagraficaRI_QNAME = new QName("", "RicercaAnagraficaRI");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.vidoc.registro.imprese.request.ricerca.anagrafica
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KCodFiscType }
     * 
     */
    public KCodFiscType createKCodFiscType() {
        return new KCodFiscType();
    }

    /**
     * Create an instance of {@link ListaImpreseRIType }
     * 
     */
    public ListaImpreseRIType createListaImpreseRIType() {
        return new ListaImpreseRIType();
    }

    /**
     * Create an instance of {@link PerChiaveReaType }
     * 
     */
    public PerChiaveReaType createPerChiaveReaType() {
        return new PerChiaveReaType();
    }

    /**
     * Create an instance of {@link PerPIvaImpresaType }
     * 
     */
    public PerPIvaImpresaType createPerPIvaImpresaType() {
        return new PerPIvaImpresaType();
    }

    /**
     * Create an instance of {@link AvanzataPerCodFiscImpresaType }
     * 
     */
    public AvanzataPerCodFiscImpresaType createAvanzataPerCodFiscImpresaType() {
        return new AvanzataPerCodFiscImpresaType();
    }

    /**
     * Create an instance of {@link PerDenominazioneOldType }
     * 
     */
    public PerDenominazioneOldType createPerDenominazioneOldType() {
        return new PerDenominazioneOldType();
    }

    /**
     * Create an instance of {@link RicercaAnagraficaRIType }
     * 
     */
    public RicercaAnagraficaRIType createRicercaAnagraficaRIType() {
        return new RicercaAnagraficaRIType();
    }

    /**
     * Create an instance of {@link PerCodFiscImpresaType }
     * 
     */
    public PerCodFiscImpresaType createPerCodFiscImpresaType() {
        return new PerCodFiscImpresaType();
    }

    /**
     * Create an instance of {@link KReaType }
     * 
     */
    public KReaType createKReaType() {
        return new KReaType();
    }

    /**
     * Create an instance of {@link PerDenominazioneEComuneSedeType }
     * 
     */
    public PerDenominazioneEComuneSedeType createPerDenominazioneEComuneSedeType() {
        return new PerDenominazioneEComuneSedeType();
    }

    /**
     * Create an instance of {@link PerDenominazioneType }
     * 
     */
    public PerDenominazioneType createPerDenominazioneType() {
        return new PerDenominazioneType();
    }

    /**
     * Create an instance of {@link PerCognomeNomeDenomType }
     * 
     */
    public PerCognomeNomeDenomType createPerCognomeNomeDenomType() {
        return new PerCognomeNomeDenomType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RicercaAnagraficaRIType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RicercaAnagraficaRI")
    public JAXBElement<RicercaAnagraficaRIType> createRicercaAnagraficaRI(RicercaAnagraficaRIType value) {
        return new JAXBElement<RicercaAnagraficaRIType>(_RicercaAnagraficaRI_QNAME, RicercaAnagraficaRIType.class, null, value);
    }

}
