//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 05:57:20 PM CEST 
//


package it.vidoc.registro.imprese.ricerca.anagrafica.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PerDenominazioneOldType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PerDenominazioneOldType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DenominazioneOld" type="{}DenominazioneType"/>
 *         &lt;element name="Cciaa" type="{}CciaaType" maxOccurs="15" minOccurs="0"/>
 *         &lt;element name="NatGiu" type="{}NatGiuType" maxOccurs="5" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PerDenominazioneOldType", propOrder = {
    "denominazioneOld",
    "cciaa",
    "natGiu"
})
public class PerDenominazioneOldType {

    @XmlElement(name = "DenominazioneOld", required = true)
    protected String denominazioneOld;
    @XmlElement(name = "Cciaa", required = true)
    protected List<String> cciaa;
    @XmlElement(name = "NatGiu", required = true)
    protected List<String> natGiu;

    /**
     * Gets the value of the denominazioneOld property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominazioneOld() {
        return denominazioneOld;
    }

    /**
     * Sets the value of the denominazioneOld property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominazioneOld(String value) {
        this.denominazioneOld = value;
    }

    /**
     * Gets the value of the cciaa property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cciaa property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCciaa().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCciaa() {
        if (cciaa == null) {
            cciaa = new ArrayList<String>();
        }
        return this.cciaa;
    }

    /**
     * Gets the value of the natGiu property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the natGiu property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNatGiu().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNatGiu() {
        if (natGiu == null) {
            natGiu = new ArrayList<String>();
        }
        return this.natGiu;
    }

}
