//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.26 at 05:57:20 PM CEST 
//


package it.vidoc.registro.imprese.ricerca.anagrafica.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PerDenominazioneEComuneSedeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PerDenominazioneEComuneSedeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Denominazione" type="{}DenominazioneType"/>
 *         &lt;element name="Cciaa" type="{}CciaaType"/>
 *         &lt;element name="CodComSede" type="{}CodComType"/>
 *         &lt;element name="NatGiu" type="{}NatGiuType" maxOccurs="5" minOccurs="0"/>
 *         &lt;element name="IStatoImpresa" type="{}IStatoImpresaType" minOccurs="0"/>
 *         &lt;element name="FNoRd" type="{}FNoRdType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PerDenominazioneEComuneSedeType", propOrder = {
    "denominazione",
    "cciaa",
    "codComSede",
    "natGiu",
    "iStatoImpresa",
    "fNoRd"
})
public class PerDenominazioneEComuneSedeType {

    @XmlElement(name = "Denominazione", required = true)
    protected String denominazione;
    @XmlElement(name = "Cciaa", required = true)
    protected String cciaa;
    @XmlElement(name = "CodComSede", required = true)
    protected String codComSede;
    @XmlElement(name = "NatGiu", required = true)
    protected List<String> natGiu;
    @XmlElement(name = "IStatoImpresa")
    protected IStatoImpresaType iStatoImpresa;
    @XmlElement(name = "FNoRd")
    protected String fNoRd;

    /**
     * Gets the value of the denominazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominazione() {
        return denominazione;
    }

    /**
     * Sets the value of the denominazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominazione(String value) {
        this.denominazione = value;
    }

    /**
     * Gets the value of the cciaa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCciaa() {
        return cciaa;
    }

    /**
     * Sets the value of the cciaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCciaa(String value) {
        this.cciaa = value;
    }

    /**
     * Gets the value of the codComSede property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodComSede() {
        return codComSede;
    }

    /**
     * Sets the value of the codComSede property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodComSede(String value) {
        this.codComSede = value;
    }

    /**
     * Gets the value of the natGiu property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the natGiu property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNatGiu().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNatGiu() {
        if (natGiu == null) {
            natGiu = new ArrayList<String>();
        }
        return this.natGiu;
    }

    /**
     * Gets the value of the iStatoImpresa property.
     * 
     * @return
     *     possible object is
     *     {@link IStatoImpresaType }
     *     
     */
    public IStatoImpresaType getIStatoImpresa() {
        return iStatoImpresa;
    }

    /**
     * Sets the value of the iStatoImpresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link IStatoImpresaType }
     *     
     */
    public void setIStatoImpresa(IStatoImpresaType value) {
        this.iStatoImpresa = value;
    }

    /**
     * Gets the value of the fNoRd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFNoRd() {
        return fNoRd;
    }

    /**
     * Sets the value of the fNoRd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFNoRd(String value) {
        this.fNoRd = value;
    }

}
